# Your list of challenges with "name" and "key"
predefined_challenges = [
    {"name": "A Land of Opportunities missions completed", "key": "mpgc_story_mission_wins", "showgoal": "y"},
    {"name": "Alaskan Ginseng picked", "key": "mpgc_alaskan_ginseng_picked", "category": ["plants", "alaskan_ginseng"]},
    {"name": "Alligators killed", "key": "mpgc_gators_killed", "category": ["animal", "alligator_medium"]},
    {"name": "Alpine Goats skinned", "key": "mpgc_goats_skinned", "category": ["animal", "goat"]},
    {"name": "American Badgers skinned", "key": "mpgc_badgers_skinned", "category": ["animal", "badger"]},
    {"name": "American Bullfrogs collected", "key": "mpgc_bullfrogs_skinned", "category": ["animal", "frogbull"]},
    {"name": "American Ginseng picked", "key": "mpgc_american_ginseng_picked", "category": ["plants", "american_ginseng"]},
    {"name": "American Muskrats skinned", "key": "mpgc_muskrats_skinned", "category": ["animal", "muskrat"]},
    {"name": "Animal claws sold", "key": "mpgc_shop_animal_claw_sell", "category": ["shops", "butcher"], "showgoal": "y",
     "description": "Talons also work"},
    {"name": "Animal meat sold", "key": "mpgc_shop_animal_meat_sell", "category": ["shops", "butcher"]},
    {"name": "Animal teeth sold", "key": "mpgc_shop_animal_teeth_sell", "category": ["shops", "butcher"], "showgoal": "y"},
    {"name": "Animals killed with a Bow", "key": "mpgc_animal_bow_kills"},
    {"name": "Animals killed with a knife", "key": "mpgc_animal_knife_kills"},
    {"name": "Animals killed with a Throwing Weapon", "key": "mpgc_animal_throwing_kills",
             "description": "Go to Valentine, then follow the railway line south to Flatneck Station.\nThe pigs in the pens are easy targets for something like the melee hatchet.\nOr go to Tumbleweed, then Rathskeller Fork to the north. Chickens and goats make a soft target."},
    {"name": "Animals killed", "key": "mpgc_animal_kills"},
    {"name": "Animals skinned", "key": "mpgc_animals_skinned"},
    {"name": "Animals stowed on horseback", "key": "mpgc_horse_stowed_animals"},
    {"name": "Animals trampled", "key": "mpgc_horse_animals_trampled"},
    {"name": "Anthony Foreman missions completed", "key": "mpgc_gfh_anthony_foreman_wins", "category": ["gfh", "anthony_foreman"], "showgoal": "y"},
    {"name": "Banded Gila Monsters skinned", "key": "mpgc_gilamonster_skinned", "category": ["animal", "gilamonster"]},
    {"name": "Bay Bolete picked", "key": "mpgc_bay_bolete_picked", "category": ["plants", "bay_bolete"]},
    {"name": "Bears killed", "key": "mpgc_bears_killed", "category": ["animal", "bear_black"], "showgoal": "y"},
    {"name": "Beavers skinned", "key": "mpgc_beavers_skinned", "category": ["animal", "beaver"]},
    {"name": "Belt Buckle updated", "key": "mpgc_customization_belt_buckle", "category": ["shops", "tailor"], "showgoal": "y"},
    {"name": "Biggest Fish Contest completed", "key": "mpgc_posse_fish_challenge_completed"},
    {"name": "Bird Shooting Contest completed", "key": "mpgc_posse_bird_challenge_completed"},
    {"name": "Bison skinned", "key": "mpgc_buffalo_skinned", "category": ["animal", "buffalo"]},
    {"name": "Black-tailed Jackrabbits skinned", "key": "mpgc_rabbits_skinned", "category": ["animal", "rabbit"]},
    {"name": "Blackberries picked", "key": "mpgc_black_berry_picked", "category": ["plants", "black_berry"],
             "description": "Go to Mazanita Post. \nSome just to the north west of the main building, then head directly east across the road and into the trees for more."},
    {"name": "Blackcurrants picked", "key": "mpgc_black_currant_picked", "category": ["plants", "black_currant"]},
    {"name": "Blood Money Crimes completed", "key": "mpgc_outlaw_mission_wins", "showgoal": "y",
             "description": "Anthony Foreman just by Rhodes station is the easiest to get to."},
    {"name": "Bluegill caught", "key": "mpgc_fish_caught_bluegill", "category": ["fish", "bluegill"]},
    {"name": "Boars skinned", "key": "mpgc_boars_skinned", "category": ["animal", "boar"]},
    {"name": "Bonnie MacFarlane missions completed", "key": "mpgc_gfh_bonnie_macfarlane_wins", "category": ["gfh", "bonnie"], "showgoal": "y"},
    {"name": "Bullhead Catfish caught", "key": "mpgc_fish_caught_bullhead_catfish", "category": ["fish", "bullheadcatfish"],
             "description": "Head to Lagras and then go a few metres south to the water by the fishing boat.<\nUse corn for bait."},
    {"name": "Bulls skinned", "key": "mpgc_bulls_skinned", "category": ["animal", "bull_devon"]},
    {"name": "Burdock Roots picked", "key": "mpgc_burdock_root_picked", "category": ["plants", "burdock_root"]},
    {"name": "Camp themes updated", "key": "mpgc_customization_camp_style"},
    {"name": "Candies eaten", "key": "mpgc_consumable_candy_eaten", "category": ["shops", "general_store"]},
    {"name": "Canned food eaten", "key": "mpgc_consumable_canned_goods_eaten", "category": ["shops", "general_store"]},
    {"name": "Capitale notes collected", "key": "mpgc_capitale_notes_collected",
             "description": "The Blood Money contract, 'Railroad Contract' is a very good one to find capitale.\nPart 1 has some in a box at the campsite for example."},
    {"name": "Cats photographed", "key": "mpgc_photograph_cat"},
    {"name": "Chain Pickerel caught", "key": "mpgc_fish_caught_chain_pickerel", "category": ["fish", "chainpickerel"]},
    {"name": "Channel Catfish caught", "key": "mpgc_fish_caught_channel_catfish", "category": ["fish", "channelcatfish"]},
    {"name": "Chanterelle picked", "key": "mpgc_chanterelle_picked", "category": ["plants", "chanterelles"]},
    {"name": "Chickens skinned", "key": "mpgc_chickens_skinned", "category": ["animal", "chicken_leghorn"]},
    {"name": "Clothing style updated", "key": "mpgc_customization_clothing_style", "category": ["shops", "tailor"]},
    {"name": "Collared Peccaries skinned", "key": "mpgc_javelina_skinned", "category": ["animal", "javelina"]},
    {"name": "Common Bulrush picked", "key": "mpgc_common_bulrush_picked", "category": ["plants", "common_bulrush"]},
    {"name": "Complimentary snacks eaten at a Saloon", "key": "mpgc_consumable_saloon_snacks_eaten", "category": ["shops", "saloon"]},
    {"name": "Condors plucked", "key": "mpgc_condor_skinned", "category": ["animal", "californiancondor"]},
    {"name": "Cooked Seasoned Big Game", "key": "mpgc_craft_big_game_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cooked Seasoned Crustacean", "key": "mpgc_craft_crustacean_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cooked Seasoned Exotic Bird", "key": "mpgc_craft_exotic_bird_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cooked Seasoned Flaky Fish", "key": "mpgc_craft_flakey_fish_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cooked Seasoned Game", "key": "mpgc_craft_game_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cooked Seasoned Mutton", "key": "mpgc_craft_mutton_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cooked Seasoned Plump Bird", "key": "mpgc_craft_plump_bird_seasoned", "category": ["menu", "campfires"],
             "description": "Chickens and Turkeys give plump bird meat when plucked."},
    {"name": "Cooked Seasoned Pork", "key": "mpgc_craft_pork_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cooked Seasoned Prime Beef", "key": "mpgc_craft_prime_beef_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cooked Seasoned Succulent Fish", "key": "mpgc_craft_succulent_fish_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cooked Seasoned Venison", "key": "mpgc_craft_venison_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cormorants plucked", "key": "mpgc_cormorant_skinned", "category": ["animal", "cormorant_doublecrested"]},
    {"name": "Cougars killed", "key": "mpgc_cougars_killed", "category": ["animal", "cougar"]},
    {"name": "Cows skinned", "key": "mpgc_cows_skinned", "category": ["animal", "cow"]},
    {"name": "Coyotes skinned", "key": "mpgc_coyotes_skinned", "category": ["animal", "coyote"]},
    {"name": "Crafted a horse care item", "key": "mpgc_craft_horse_care", "category": ["menu", "campfires"]},
    {"name": "Crafted a Tonic", "key": "mpgc_craft_tonic", "category": ["menu", "campfires"]},
    {"name": "Creeping Thyme picked", "key": "mpgc_creeping_thyme_picked", "category": ["plants", "creeping_thyme"]},
    {"name": "Cups of coffee drunk", "key": "mpgc_consumable_coffee_drunk", "category": ["shops", "general_store"]},
    {"name": "Deer skinned", "key": "mpgc_deer_skinned", "category": ["animal", "deer"],
             "description": "Deer are fairly common over most of New Hanover, West Elizabeth and Lemoyne. Scarlett Meadows, Big Valley and to the East of Emerald station are all good spots. Please note that Pronghorns do not count. It has to be Whitetail’s. A Whitetail Buck will count though."},
    {"name": "Defended a campsite", "key": "mpgc_dynamic_campsite_defend", "category": ["menu", "defend_campsite"]},
    {"name": "Desert Sage picked", "key": "mpgc_desert_sage_picked", "category": ["plants", "desert_sage"]},
    {"name": "Distance driven a train", "key": "mpgc_distance_driven_train", "category": ["menu", "trains"]},
    {"name": "Distance non-player enemy dragged from horseback", "key": "mpgc_lasso_enemy_horseback_dragged"},
    {"name": "Distance ran", "key": "mpgc_distance_run"},
    {"name": "Distance rowed a boat or canoe", "key": "mpgc_distance_rowed_boat", "category": ["menu", "boats"]},
    {"name": "Distance swam", "key": "mpgc_distance_swim"},
    {"name": "Distance traveled by coach or wagon", "key": "mpgc_distance_coach"},
    {"name": "Distance traveled by train", "key": "mpgc_distance_train", "category": ["menu", "trains"]},
    {"name": "Distance traveled by wagon with a Posse Member", "key": "mpgc_distance_companion_wagon"},
    {"name": "Distance traveled in boat with a Posse Member", "key": "mpgc_distance_companion_boat", "category": ["menu", "boats"]},
    {"name": "Distance traveled leading own horse", "key": "mpgc_distance_led_horse"},
    {"name": "Distance traveled on a mount with a Posse Member", "key": "mpgc_distance_companion_horse"},
    {"name": "Distance traveled on mount", "key": "mpgc_distance_mount"},
    {"name": "Distance traveled", "key": "mpgc_distance_any"},
    {"name": "Dogs photographed", "key": "mpgc_photograph_dog", "category": ["animal", "dog_street"]},
    {"name": "Don't reach high Hostility within one game day", "key": "mpgc_notoriety_no_hostility_timed"},
    {"name": "Drinks ordered at a Saloon", "key": "mpgc_consumable_drinks_ordered_saloon", "category": ["shops", "saloon"]},
    {"name": "Dry goods eaten", "key": "mpgc_consumable_dry_goods_eaten", "category": ["shops", "general_store"]},
    {"name": "Ducks skinned", "key": "mpgc_ducks_skinned", "category": ["animal", "duck_mallard"]},
    {"name": "Eagles plucked", "key": "mpgc_eagles_skinned", "category": ["animal", "eagle_golden"]},
    {"name": "Egrets skinned", "key": "mpgc_egret_skinned", "category": ["animal", "egret_reddish"]},
    {"name": "Elk skinned", "key": "mpgc_elk_skinned", "category": ["animal", "elk_rocky"]},
    {"name": "English Mace picked", "key": "mpgc_english_mace_picked", "category": ["plants", "english_mace"],
             "description": "Head along the path from McFarlane's Ranch Station up towards Harriet. \nNear her are a number of patches of English Mace."},
    {"name": "Escaped the law", "key": "mpgc_law_lose_wanted"},
    {"name": "Evergreen Huckleberries picked", "key": "mpgc_evergreen_huckleberry_picked", "category": ["plants", "evergreen_huckleberry"]},
    {"name": "Facial appearance updated at a Barber", "key": "mpgc_customization_facial_appearance", "category": ["shops", "barber"]},
    {"name": "Feathers sold", "key": "mpgc_shop_feathers_sell", "category": ["shops", "butcher"]},
    {"name": "Finish a mode in Featured Series", "key": "mpgc_series_featured_attempts"},
    {"name": "Finish Race in Race Series", "key": "mpgc_series_race_attempts"},
    {"name": "Finish Showdown in any Showdown Series", "key": "mpgc_series_adversarial_attempts"},
    {"name": "Finish Showdown in Elimination Series", "key": "mpgc_series_elimination_attempts"},
    {"name": "Finish Showdown in Shootout Series", "key": "mpgc_series_shootout_attempts"},
    {"name": "Finish Showdown in Takeover Series", "key": "mpgc_series_takeover_attempts"},
    {"name": "Fish caught weighing at least 5 lbs (2.2 kg)", "key": "mpgc_fish_size_caught", "category": ["shops", "tackle"]},
    {"name": "Fish caught with a lure", "key": "mpgc_fish_caught_lure", "category": ["shops", "tackle"]},
    {"name": "Fish caught with food", "key": "mpgc_fish_caught_food", "category": ["shops", "tackle"]},
    {"name": "Fish caught with live bait", "key": "mpgc_fish_caught_live_bait", "category": ["shops", "tackle"]},
    {"name": "Fish caught", "key": "mpgc_fish_caught", "category": ["shops", "tackle"]},
    {"name": "Flying birds killed while on a moving train", "key": "mpgc_flying_bird_train_kills"},
    {"name": "Flying birds killed with a sniper rifle", "key": "mpgc_flying_bird_kills_sniper"},
    {"name": "Flying birds killed", "key": "mpgc_flying_bird_kills"},
    {"name": "Followed dog to something interesting", "key": "mpgc_dynamic_hobo_dog", "category": ["menu", "dog_encounter"],
             "description": "Can usually find one south of Armadillo when doing a moonshine delivery. \nSolo lobbies more likely as well of course. "},
    {"name": "Foxes skinned", "key": "mpgc_foxes_skinned", "category": ["animal", "fox_red"]},
    {"name": "Free Roam Events played", "key": "mpgc_fme_attempts"},
    {"name": "Free Roam missions completed", "key": "mpgc_gfh_wins"},
    {"name": "Fresh produce eaten", "key": "mpgc_consumable_fresh_produce_eaten", "category": ["shops", "general_store"]},
    {"name": "Geese skinned", "key": "mpgc_goose_skinned", "category": ["animal", "goosecanada"]},
    {"name": "Go On-Call and complete a Story mission", "key": "mpgc_story_mission_wins_on_call"},
    {"name": "Golden Currants picked", "key": "mpgc_golden_currant_picked", "category": ["plants", "golden_currant"]},
    {"name": "Hairstyle updated", "key": "mpgc_customization_hairstyle", "category": ["shops", "barber"]},
    {"name": "Hamish Sinclair missions completed", "key": "mpgc_gfh_hamish_sinclair_wins", "category": ["gfh", "war_vet"]},
    {"name": "Hawks plucked", "key": "mpgc_hawks_skinned", "category": ["animal", "hawk_ferruginous"],
             "description": "Rathskeller Fork often has a hawk on the roof of the western building."},
    {"name": "Helped someone in need", "key": "mpgc_dynamic_rescue_escort_ped", "category": ["menu", "rescue"]},
    {"name": "Herb Picking Contest completed", "key": "mpgc_posse_herb_challenge_completed"},
    {"name": "Herbs eaten", "key": "mpgc_consumable_herbs_tasted", "category": ["shops", "doctor"]},
    {"name": "Herbs sold", "key": "mpgc_shop_herbs_sell", "category": ["shops", "doctor"]},
    {"name": "Herons skinned", "key": "mpgc_herons_skinned", "category": ["animal", "heron_greatblue"]},
    {"name": "Hideouts cleared", "key": "mpgc_hideout_clear", "category": ["menu", "hideouts"]},
    {"name": "Horse appearance updated", "key": "mpgc_customization_horse_style", "category": ["shops", "stable"]},
    {"name": "Horse tack updated", "key": "mpgc_customization_horse_kit", "category": ["shops", "stable"],
             "description": "At any stable, select Horses, then Tack and Services, then Saddles, and pick your existing ticked saddle.\nThat should trigger the challenge, you don't need to alter anything."},
    {"name": "Horse tonics used", "key": "mpgc_horse_tonics_given"},
    {"name": "Horses fed", "key": "mpgc_horse_fed"},
    {"name": "Hummingbird Sage picked", "key": "mpgc_hummingbird_sage_picked", "category": ["plants", "hummingbird_sage"]},
    {"name": "Hunt the Leader completed", "key": "mpgc_posse_hunt_posse_leader_attempts"},
    {"name": "Iguanas skinned", "key": "mpgc_iguanas_skinned", "category": ["animal", "iguanadesert"]},
    {"name": "Indian Tobacco picked", "key": "mpgc_indian_tobacco_picked", "category": ["plants", "indian_tobacco"]},
    {"name": "Items sold to a Fence", "key": "mpgc_shop_sell_to_fence", "category": ["shops", "fence"]},
    {"name": "Items sold to Gus", "key": "mpgc_shop_sell_to_trapper", "category": ["shops", "trapper"]},
    {"name": "James Langton missions completed", "key": "mpgc_gfh_james_langton_wins", "category": ["gfh", "langton"]},
    {"name": "Joe missions completed", "key": "mpgc_gfh_joe_wins", "category": ["gfh", "joe"]},
    {"name": "Jumped from a horse onto a moving train", "key": "mpgc_horse_jump_to_train", "category": ["menu", "trains"]},
    {"name": "Jumped from a horse to a moving wagon", "key": "mpgc_horse_jump_to_wagon"},
    {"name": "Jumped from a horse to another horse", "key": "mpgc_horse_jump_to_horse"},
    {"name": "Jumped onto a horse from a 3m height", "key": "mpgc_horse_jump_from_height", "showgoal": "n"},
    {"name": "Lake Sturgeon caught", "key": "mpgc_fish_caught_lake_sturgeon", "category": ["fish", "lake_sturgeon"]},
    {"name": "Largemouth Bass caught", "key": "mpgc_fish_caught_largemouth_bass", "category": ["fish", "largemouthbass"]},
    {"name": "Little Brown Bats collected", "key": "mpgc_bats_skinned", "category": ["animal", "bat"]},
    {"name": "Longnose Gar caught", "key": "mpgc_fish_caught_longnose_gar", "category": ["fish", "longnosegar"]},
    {"name": "Loons skinned", "key": "mpgc_loon_skinned", "category": ["animal", "loon_pacific"]},
    {"name": "Masks worn", "key": "mpgc_customization_mask", "category": ["shops", "tailor"]},
    {"name": "Meats eaten", "key": "mpgc_consumable_meat_eaten", "category": ["shops", "butcher"]},
    {"name": "Milkweed picked", "key": "mpgc_milkweed_picked", "category": ["plants", "milkweed"]},
    {"name": "Moose skinned", "key": "mpgc_moose_skinned", "category": ["animal", "moose"]},
    {"name": "Multiple Player kills in 5 sec. in Free Roam Events", "key": "mpgc_players_killed_fme_timer"},
    {"name": "Multiple Player kills in 5 seconds in Posse Versus", "key": "mpgc_players_killed_pv_timer"},
    {"name": "Multiple Player kills in 5 seconds in Showdowns", "key": "mpgc_players_killed_showdown_timer"},
    {"name": "Muskie caught", "key": "mpgc_fish_caught_muskie", "category": ["fish", "muskie_clear"],
             "description": "Ride west out of Strawberry to Owanjilla. \nRide all the way along the shore of the lake to the very western end where the little waterfall is. \nThis is a great spot to fish for Muskies. You will need a lure or a spinner to target these larger fish."},
    {"name": "Nine-banded Armadillos skinned", "key": "mpgc_armadillo_skinned", "category": ["animal", "armadillo"]},
    {"name": "Non-player enemies grappled to the ground", "key": "mpgc_enemies_grappled_to_ground"},
    {"name": "Non-player enemies killed at long range", "key": "mpgc_enemies_killed_from_long_distance",
             "description": "Revenue Agents at a roadblock, Trader Resupply Mission NPC's, or Del Lobo's at Thieves Landing.\nThese are all good targets, best with a scoped rifle.\nLook for the XP award notification to see if they count as a distance kill."},
    {"name": "Non-player enemies killed from cover", "key": "mpgc_enemies_killed_cover"},
    {"name": "Non-player enemies killed from the hip", "key": "mpgc_enemies_killed_from_hip"},
    {"name": "Non-player enemies killed while in Dead Eye", "key": "mpgc_enemies_killed_deadeye"},
    {"name": "Non-player enemies killed while not seen", "key": "mpgc_enemies_killed_stealth",
             "description": "Kill NPCs stealthily. Your Bow & throwing knives are your friend here. Thieves Landing is a good location in free roam. Also the legendary bounty hunter missions or the story mission ‘Where your morals lead you’ is good for stealth kills"},
    {"name": "Non-player enemies killed with a Maxim Gun", "key": "mpgc_enemies_killed_gatling_maxim", "category": ["menu", "hideouts"]},
    {"name": "Non-player enemies knocked out", "key": "mpgc_enemies_knocked_out"},
    {"name": "Non-player enemies lassoed from horseback", "key": "mpgc_lasso_enemy_horseback"},
    {"name": "Non-player enemies looted", "key": "mpgc_enemies_looted"},
    {"name": "Non-player enemies trampled", "key": "mpgc_horse_enemies_trampled",
             "description": "Trample NPCs with your horse. Thieves Landing NPCs are good for this one, or enemies in bounty missions or resupply missions. If you want to be “artistic” about it hogtie 5 NPCs and put them in a line and ride over them"},
    {"name": "Non-player enemy hats shot off", "key": "mpgc_enemy_hats_shot_off"},
    {"name": "North American Raccoons skinned", "key": "mpgc_raccoons_skinned", "category": ["animal", "racoon"]},
    {"name": "Northern Pike caught", "key": "mpgc_fish_northern_pike", "category": ["fish", "northernpike"]},
    {"name": "Oleander Sage picked", "key": "mpgc_oleander_picked", "category": ["plants", "oleander_sage"]},
    {"name": "Oregano picked", "key": "mpgc_oregano_picked", "category": ["plants", "oregano"]},
    {"name": "Other players photographed", "key": "mpgc_photograph_player"},
    {"name": "Owls plucked", "key": "mpgc_owls_skinned", "category": ["animal", "owl_great"]},
    {"name": "Oxen skinned", "key": "mpgc_oxen_skinned", "category": ["animal", "ox_angus"]},
    {"name": "Panthers killed", "key": "mpgc_panthers_killed", "category": ["animal", "panther"]},
    {"name": "Parasol Mushrooms picked", "key": "mpgc_parasol_mushroom_picked", "category": ["plants", "parasol_mushroom"]},
    {"name": "Pelicans plucked", "key": "mpgc_pelicans_skinned", "category": ["animal", "pelican_white"]},
    {"name": "Perch caught", "key": "mpgc_fish_caught_perch", "category": ["fish", "perch"],
             "description": "Perch can be caught in most Northern lakes and rivers. Bread is the best bait and definitely in sunny weather. \nA good spot is the pond in front of the abandoned sect building north of Emerald Station.\nThe Dakota River near Cumberland Forest is a good stretch. So is Roanoke Valley. \nO'Creagh's Run, Cattail Pond, Owanjila. "},
    {"name": "Perfect pelts sold", "key": "mpgc_shop_pelt_pristine_sell", "category": ["shops", "butcher"]},
    {"name": "Petted a dog", "key": "mpgc_dog_pat", "category": ["animal", "dog_street"]},
    {"name": "Pheasants skinned", "key": "mpgc_pheasants_skinned", "category": ["animal", "pheasant_ringneck"],
             "description": "Just SE of Valentine on the road by the turn off to the serial killers cabin is a great spot. \nLook in the trees where the path curves under the road."},
    {"name": "Photographed your horse", "key": "mpgc_photograph_your_horse"},
    {"name": "Pigs skinned", "key": "mpgc_pigs_skinned", "category": ["animal", "pig_berkshire"]},
    {"name": "Placed top 3 in a Race", "key": "mpgc_race_wins"},
    {"name": "Placed top 3 in a Shootout Showdown", "key": "mpgc_series_shootout_wins"},
    {"name": "Placed top 3 in a Showdown", "key": "mpgc_showdown_wins"},
    {"name": "Placed top 3 in a Takeover Showdown", "key": "mpgc_series_takeover_wins"},
    {"name": "Placed top 3 in an Elimination Showdown", "key": "mpgc_series_elimination_wins"},
    {"name": "Placed top 3 with a score in Free Roam Events", "key": "mpgc_fme_wins"},
    {"name": "Player headshot kills in Free Roam Events", "key": "mpgc_players_headshot_fme"},
    {"name": "Player headshot kills in Posse Versus", "key": "mpgc_players_headshot_pv"},
    {"name": "Player headshot kills in Showdowns", "key": "mpgc_players_headshot_showdown"},
    {"name": "Player kills from cover in Free Roam Events", "key": "mpgc_players_cover_fme"},
    {"name": "Player kills from cover in Showdowns", "key": "mpgc_players_cover_showdown"},
    {"name": "Player kills from the hip in Free Roam Events", "key": "mpgc_players_killed_from_hip_fme"},
    {"name": "Player kills from the hip in Showdowns", "key": "mpgc_players_killed_from_hip_showdown"},
    {"name": "Player kills in Dead Eye in Free Roam Events", "key": "mpgc_players_deadeye_fme"},
    {"name": "Player kills in Dead Eye in Showdowns", "key": "mpgc_players_deadeye_showdown"},
    {"name": "Player kills in Free Roam Events", "key": "mpgc_players_killed_fme"},
    {"name": "Player kills in Posse Versus", "key": "mpgc_players_killed_pv"},
    {"name": "Player kills in Showdowns", "key": "mpgc_players_killed_showdown"},
    {"name": "Player kills with a Bow in Free Roam Events", "key": "mpgc_players_killed_bow_fme"},
    {"name": "Player kills with a Bow in Showdowns", "key": "mpgc_players_killed_bow_showdown"},
    {"name": "Player kills with a Pistol in Free Roam Events", "key": "mpgc_players_killed_pistol_fme"},
    {"name": "Player kills with a Pistol in Showdowns", "key": "mpgc_players_killed_pistol_showdown"},
    {"name": "Player kills with a Repeater in Free Roam Events", "key": "mpgc_players_killed_repeater_fme"},
    {"name": "Player kills with a Repeater in Showdowns", "key": "mpgc_players_killed_repeater_showdown"},
    {"name": "Player kills with a Revolver in Free Roam Events", "key": "mpgc_players_killed_revolver_fme"},
    {"name": "Player kills with a Revolver in Showdowns", "key": "mpgc_players_killed_revolver_showdown"},
    {"name": "Player kills with a Rifle in Free Roam Events", "key": "mpgc_players_killed_rifle_fme"},
    {"name": "Player kills with a Rifle in Showdowns", "key": "mpgc_players_killed_rifle_showdown"},
    {"name": "Player kills with a Shotgun in Free Roam Events", "key": "mpgc_players_killed_shotgun_fme"},
    {"name": "Player kills with a Shotgun in Showdowns", "key": "mpgc_players_killed_shotgun_showdown"},
    {"name": "Player kills with explosives in Free Roam Events", "key": "mpgc_players_killed_explosives_fme"},
    {"name": "Player kills with explosives in Showdowns", "key": "mpgc_players_killed_explosives_showdown"},
    {"name": "Player kills with melee in Free Roam Events", "key": "mpgc_players_killed_melee_fme"},
    {"name": "Player kills with melee in Showdowns", "key": "mpgc_players_killed_melee_showdown"},
    {"name": "Player kills with throwing weapons in Showdowns", "key": "mpgc_players_killed_throw_showdown"},
    {"name": "Player kills with thrown weapons in Free Roam Events", "key": "mpgc_players_killed_throw_fme"},
    {"name": "Player stats boosted by tonics", "key": "mpgc_consumable_tonics_oils_used", "category": ["shops", "general_store"]},
    {"name": "Players headshot with a Bow in Free Roam Events", "key": "mpgc_players_headshot_bow_fme"},
    {"name": "Players headshot with a Bow in Showdowns", "key": "mpgc_players_headshot_bow_showdown"},
    {"name": "Players revived", "key": "mpgc_players_revived"},
    {"name": "Posse Infighting completed", "key": "mpgc_posse_infighting_completed"},
    {"name": "Posse Races completed", "key": "mpgc_posse_race_attempts"},
    {"name": "Posses joined", "key": "mpgc_posse_join", "showgoal": "y"},
    {"name": "Prairie Chickens skinned", "key": "mpgc_prairiechicken_skinned", "category": ["animal", "prairiechicken"]},
    {"name": "Prairie Poppies picked", "key": "mpgc_prairie_poppy_picked", "category": ["plants", "prairie_poppy"]},
    {"name": "Pronghorns skinned", "key": "mpgc_pronghorns_skinned", "category": ["animal", "pronghorn_american_m"]},
    {"name": "Provisions cooked at campfires", "key": "mpgc_craft_food", "category": ["menu", "campfires"]},
    {"name": "Put a mask on your horse", "key": "mpgc_customization_horse_mask", "category": ["shops", "stable"]},
    {"name": "Ram's Head picked", "key": "mpgc_rams_head_picked", "category": ["plants", "rams_head"],
             "description": "Cumberland Forest is a great place to look for Rams Head. There are a couple of patches of them just below the letter ‘C’ at the beginning of the word Cumberland on the map. There is another patch where the letter ‘M’ is too. Another good place to get them is north of the path that runs above the letters ‘U’ and ‘M’"},
    {"name": "Rams skinned", "key": "mpgc_rams_skinned", "category": ["animal", "bighornram_desert"],
             "description": "Can be difficult. South of Tumbleweed, look near the letter E in New Austin on the map.\nAnother good spot to try is the north-west end of Big Valley, past the house on stilts.\nCattail Pond, west of Valentine, is also a good spot to find them."},
    {"name": "Raspberries picked", "key": "mpgc_red_raspberry_picked", "category": ["plants", "red_raspberry"]},
    {"name": "Rats collected", "key": "mpgc_rats_skinned", "category": ["animal", "rat_black"]},
    {"name": "Red Sage picked", "key": "mpgc_red_sage_picked", "category": ["plants", "red_sage"]},
    {"name": "Redfin Pickerel caught", "key": "mpgc_fish_caught_redfin_pickerel", "category": ["fish", "redfinpickerel"]},
    {"name": "Rock Bass caught", "key": "mpgc_fish_caught_rock_bass", "category": ["fish", "rockbass"]},
    {"name": "Roosters skinned", "key": "mpgc_roosters_skinned", "category": ["animal", "rooster_dominique"]},
    {"name": "Sadie Adler missions completed", "key": "mpgc_gfh_sadie_adler_wins", "category": ["gfh", "sadie_adler"]},
    {"name": "Seagulls plucked", "key": "mpgc_seagulls_skinned", "category": ["animal", "seagull_herring"]},
    {"name": "Sean Macguire missions completed", "key": "mpgc_gfh_sean_macquire_wins", "category": ["gfh", "sean_macquire"], "showgoal": "y"},
    {"name": "Self portraits taken", "key": "mpgc_photograph_selfie"},
    {"name": "Shaky missions completed", "key": "mpgc_gfh_shaky_wins", "category": ["gfh", "shaky"]},
    {"name": "Sheep skinned", "key": "mpgc_sheep_skinned", "category": ["animal", "sheep"]},
    {"name": "Small animal carcasses broken down", "key": "mpgc_craft_broke_down_small_animals"},
    {"name": "Small bird carcasses collected", "key": "mpgc_songbirds_collected"},
    {"name": "Smallmouth Bass caught", "key": "mpgc_fish_caught_smallmouth_bass", "category": ["fish", "smallmouthbass"]},
    {"name": "Snakes skinned", "key": "mpgc_snakes_skinned", "category": ["animal", "snake"]},
    {"name": "Sockeye Salmon caught", "key": "mpgc_fish_caught_sockeye_salmon", "category": ["fish", "salmon_sockeye"]},
    {"name": "Spoonbills skinned", "key": "mpgc_spoonbill_skinned", "category": ["animal", "roseatespoonbill"]},
    {"name": "Squirrels collected", "key": "mpgc_squirrel_skinned", "category": ["animal", "squirrel_grey"]},
    {"name": "Steelhead Trout caught", "key": "mpgc_fish_caught_steelhead_trout", "category": ["fish", "steelheadtrout"]},
    {"name": "Stopped a runaway wagon", "key": "mpgc_dynamic_runaway_wagon", "category": ["menu", "runaway_wagon"]},
    {"name": "Striped Skunks skinned", "key": "mpgc_skunks_skinned", "category": ["animal", "skunk"]},
    {"name": "Successfully fended off an ambush", "key": "mpgc_dynamic_ambush", "category": ["menu", "ambush"]},
    {"name": "Telegram missions completed", "key": "mpgc_telegram_mission_wins"},
    {"name": "The Boy missions completed", "key": "mpgc_gfh_the_boy_wins", "category": ["gfh", "the_boy"]},
    {"name": "Times became drunk", "key": "mpgc_consumable_became_drunk", "category": ["shops", "saloon"]},
    {"name": "Tobacco smoked or chewed", "key": "mpgc_consumable_tobacco_used", "category": ["shops", "general_store"]},
    {"name": "Train clerk missions completed", "key": "mpgc_gfh_train_clerk_wins", "category": ["gfh", "wallace_train_clerk"]},
    {"name": "Treasure Maps or treasures found", "key": "mpgc_dynamic_found_treasure_or_map", "category": ["menu", "tree_map"]},
    {"name": "Turkeys skinned", "key": "mpgc_turkeys_skinned", "category": ["animal", "turkey_eastern"]},
    {"name": "Turtles skinned", "key": "mpgc_turtle_skinned", "category": ["animal", "turtle_snapping"]},
    {"name": "Types of fish caught", "key": "mpgc_fish_caught_variety", "category": ["shops", "tackle"]},
    {"name": "Used an emote on a local", "key": "mpgc_emote_npc"},
    {"name": "Used an emote on a player in Free Roam", "key": "mpgc_emote_player"},
    {"name": "Vanilla Flowers picked", "key": "mpgc_vanilla_flower_picked", "category": ["plants", "vanilla_flower"]},
    {"name": "Vaults on horseback", "key": "mpgc_horse_vaults",
             "description": "Head to Tumbleweed, there's a nice low wall right by the fast travel post that you can use to vault over."},
    {"name": "Violet Snowdrop picked", "key": "mpgc_violet_snowdrop_picked", "category": ["plants", "violet_snowdrop"],
             "description": "On the clifftop above Valentine, there's a few patches up there."},
    {"name": "Virginia Opossums skinned", "key": "mpgc_opossums_skinned", "category": ["animal", "possum"]},
    {"name": "Visited a shop in Blackwater", "key": "mpgc_shop_visit_blackwater", "category": ["shops", "general_store"]},
    {"name": "Visited a shop in Rhodes", "key": "mpgc_shop_visit_rhodes", "category": ["shops", "general_store"]},
    {"name": "Visited a shop in Saint Denis", "key": "mpgc_shop_visit_saint_denis", "category": ["shops", "general_store"]},
    {"name": "Visited a shop in Strawberry", "key": "mpgc_shop_visit_strawberry", "category": ["shops", "general_store"]},
    {"name": "Visited a shop in Tumbleweed", "key": "mpgc_shop_visit_tumbleweed", "category": ["shops", "general_store"]},
    {"name": "Visited a shop in Valentine", "key": "mpgc_shop_visit_valentine", "category": ["shops", "general_store"]},
    {"name": "Visited Annesburg and Armadillo in an hour", "key": "mpgc_travel_timed_annesburg_armadillo"},
    {"name": "Visited Bolger Glade", "key": "mpgc_travel_visit_bolger_glade", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Brandywine Drop", "key": "mpgc_travel_visit_brandywine_drop", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Colter and Saint Denis in an hour", "key": "mpgc_travel_timed_colter_saint_denis"},
    {"name": "Visited Colter", "key": "mpgc_travel_visit_colter", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Cotorra springs", "key": "mpgc_travel_visit_cotorra_springs", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Fort Mercer", "key": "mpgc_travel_visit_fort_mercer", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Fort Wallace", "key": "mpgc_travel_visit_fort_wallace", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Lagras", "key": "mpgc_travel_visit_lagras", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited MacFarlane's Ranch", "key": "mpgc_travel_visit_macfarlane_ranch", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Owanjila Dam", "key": "mpgc_travel_visit_owanjila_dam", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited the peak of Mount Hagen", "key": "mpgc_travel_visit_mount_hagen", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Valentine and Van Horn in 30 mins", "key": "mpgc_travel_timed_valentine_van_horn"},
    {"name": "Visited Van Horn", "key": "mpgc_travel_visit_van_horn", "category": ["daily_location", "daily_locations"]},
    {"name": "Vultures plucked", "key": "mpgc_vultures_skinned", "category": ["animal", "vulture_western"]},
    {"name": "Waves completed in Call to Arms", "key": "mpgc_protect_waves_completed"},
    {"name": "Weapons cleaned with Gun Oil", "key": "mpgc_customization_weapon_cleaning", "category": ["shops", "gunsmith"]},
    {"name": "Weapons customized", "key": "mpgc_customization_weapon_customization", "category": ["shops", "gunsmith"]},
    {"name": "Western Chipmunks collected", "key": "mpgc_chipmunk_skinned", "category": ["animal", "chipmunk"]},
    {"name": "Western Ravens plucked", "key": "mpgc_ravens_skinned", "category": ["animal", "raven"]},
    {"name": "Western Toads collected", "key": "mpgc_toads_skinned", "category": ["animal", "toad"],
             "description": "Follow the railway tracks north out of the city and into Bluewater Marsh.\nThe mud flats near where the railway line forks over the water is a good place to hunt for toads.\nSo is the area near the burnt out fishing shack at Copperhead Landing, just NE of that."},
    {"name": "Whole animal carcasses sold", "key": "mpgc_shop_animal_whole_sell", "category": ["shops", "butcher"]},
    {"name": "Whooping Cranes plucked", "key": "mpgc_cranewhooping_skinned", "category": ["animal", "cranewhooping_whooping"]},
    {"name": "Wild Carrots picked", "key": "mpgc_wild_carrots_picked", "category": ["plants", "wild_carrots"]},
    {"name": "Wild Feverfew picked", "key": "mpgc_wild_feverfew_picked", "category": ["plants", "wild_feverfew"]},
    {"name": "Wild Mint picked", "key": "mpgc_wild_mint_picked", "category": ["plants", "wild_mint"]},
    {"name": "Wintergreen Berries picked", "key": "mpgc_wintergreen_berry_picked", "category": ["plants", "wintergreen_berry"]},
    {"name": "Wolves killed", "key": "mpgc_wolves_killed", "category": ["animal", "wolf_gray"]},
    {"name": "Yarrow picked", "key": "mpgc_yarrow_picked", "category": ["plants", "yarrow"],
             "description": "Fast travel to Rhodes station, and on the grass area west of the platform, there are two patches of yarrow."}
]
