
category_order = [
    "predefined_challenges",
    "bounty_hunter",
    "trader",
    "collector",
    "moonshiner",
    "naturalist"
  ]



# Your list of challenges with "name" and "key"
predefined_challenges = [
    {"name": "A Land of Opportunities missions completed", "key": "mpgc_story_mission_wins", "showgoal": "yes"},
    {"name": "Alaskan Ginseng picked", "key": "mpgc_alaskan_ginseng_picked", "category": ["plants", "alaskan_ginseng"],
             "description": "South West of Wapiti there is a farm near Window Rock that grows ALASKAN Ginseng.\nThat should get you four, then head NE past the tower and follow the rock face for another plant."},
    {"name": "Alligators killed", "key": "mpgc_gators_killed", "category": ["animal", "alligator_medium"],
             "description": "Alligators are all over Lemoyne along the river banks. Follow the road north from Harriet's tent at Lagras, and just past the junction to the bridge is a good place to find resting alligators. On the coast to the east of the railway line once you're out of Saint Denis is another decent spot.", "showgoal": "yes"},
    {"name": "Alpine Goats skinned", "key": "mpgc_goats_skinned", "category": ["animal", "goat"],
             "description": "Rathskeller Fork, north of Tumbleweed, is a great place to kill two Alpine Goats."},
    {"name": "American Badgers skinned", "key": "mpgc_badgers_skinned", "category": ["animal", "badger"],
             "description": "Around Rathskeller Fork at night is a decent place to find some.\nAlso, around Riggs Station."},
    {"name": "American Bullfrogs collected", "key": "mpgc_bullfrogs_skinned", "category": ["animal", "frogbull"],
             "description": "Fast travel to Lagras, and ride past Harriet. Plenty near the junction for the bridge and around the large bend in the road.\nFurther east, you'll find some next to the railway line where the crocodiles gather as well.\nFurther north on the spur of land above Copperhead Landing, there are often bullfrogs to catch."},
    {"name": "American Ginseng picked", "key": "mpgc_american_ginseng_picked", "category": ["plants", "american_ginseng"],
             "description": "From Van Horn Mansion, follow the road southwest to the junction, there's a plant straight ahead.\nKeep going across the railway line, there's 4 plants close by."},             
    {"name": "American Muskrats skinned", "key": "mpgc_muskrats_skinned", "category": ["animal", "muskrat"],
             "description": "The San Luis River is a great place to hunt them. Some just south of Scratching Post, while the stretch below Plainview to Rio Del Lobo Rock also finds them along the river bank.\nQuite a lot of them around Bluewater Marsh as well."},
    {"name": "Animal claws sold", "key": "mpgc_shop_animal_claw_sell", "category": ["shops", "butcher"], "showgoal": "yes",
             "description": "Talons also work for this. Badgers and bears give claws when skinned.\nTake them to either a butchers or Gus to sell."},
    {"name": "Animal meat sold", "key": "mpgc_shop_animal_meat_sell", "category": ["shops", "butcher"],
             "description": "Sell at any butchers, most towns have one near the fast travel post, the easiest is Blackwater."},
    {"name": "Animal teeth sold", "key": "mpgc_shop_animal_teeth_sell", "category": ["shops", "butcher"], "showgoal": "yes",
             "description": "Alligators are pretty easy to kill and they produce teeth, so head to Lagras and follow the road north past Harriet to find some."},
    {"name": "Animals killed with a Bow", "key": "mpgc_animal_bow_kills",
             "description": "The sheep pens at Emerald Ranch are full of easy targets. There are also plenty of chickens and a couple of goats at Rathskeller Fork, north of Tumbleweed."},
    {"name": "Animals killed with a knife", "key": "mpgc_animal_knife_kills",
             "description": "Lasso animals and then use the knife to kill them.\nOr you can go straight to the sheep pens at Emerald Station under cover of darkness and get stabbing."},
    {"name": "Animals killed with a Throwing Weapon", "key": "mpgc_animal_throwing_kills",
             "description": "Go to Valentine, then follow the railway line south to Flatneck Station.\nThe pigs in the pens are easy targets for something like the melee hatchet.\nOr go to Tumbleweed, then Rathskeller Fork to the north. Chickens and goats make a soft target."},
    {"name": "Animals killed", "key": "mpgc_animal_kills",
             "description": "Chickens and goats at Rathskeller Fork, and then sheep and cows at Emerald Ranch are a good way to ramp up the numbers."},
    {"name": "Animals skinned", "key": "mpgc_animals_skinned",
             "description": "Chickens count for this one unlike most birds, so Rathskeller Fork is a great place to get a few very quickly."},
    {"name": "Animals stowed on horseback", "key": "mpgc_horse_stowed_animals"},
    {"name": "Animals trampled", "key": "mpgc_horse_animals_trampled",
             "description": "Shallow water with fish is a great way to complete this.\nSouth of Scratching Post, by the little island in the San Luis River is a good spot."},
    {"name": "Anthony Foreman missions completed", "key": "mpgc_gfh_anthony_foreman_wins", "category": ["gfh", "anthony_foreman"], "showgoal": "yes",
             "description": "Either at Radley's House near Rhodes Station, or behind Doyle's Tavern in Saint Denis."},
    {"name": "Banded Gila Monsters skinned", "key": "mpgc_gilamonster_skinned", "category": ["animal", "gilamonster"], "showgoal": "yes",
             "description": "The desert of New Austin at night is the place to find them. Head south west out of Armadillo and the junction just after Jorge's Gap where the road crosses the railway is a good area. Either side of Mercer Station should produce one at least."},
    {"name": "Bay Bolete picked", "key": "mpgc_bay_bolete_picked", "category": ["plants", "bay_bolete"],
             "description": "East of the little vegetable patch at Downes Ranch near Valentine, you'll find a few in amongst the trees."},
    {"name": "Bears killed", "key": "mpgc_bears_killed", "category": ["animal", "bear_black"], "showgoal": "yes",
             "description": "Fast travel to Manzanita Post, then travel north to the triangular junction, then head north east. You'll likely see a Grizzly Bear ahead on your left at the road side."},
    {"name": "Beavers skinned", "key": "mpgc_beavers_skinned", "category": ["animal", "beaver"],
             "description": "From Strawberry, head to Owanjia Dam, there's usually a beaver by the water as you approach. Then just keep going around the shoreline for more. Change lobbies to get more spawns. They're timid, so Blending Tonics are useful."},
    {"name": "Belt Buckle updated", "key": "mpgc_customization_belt_buckle", "category": ["shops", "tailor"], "showgoal": "yes"},
    {"name": "Biggest Fish Contest completed", "key": "mpgc_posse_fish_challenge_completed"},
    {"name": "Bird Shooting Contest completed", "key": "mpgc_posse_bird_challenge_completed"},
    {"name": "Bison skinned", "key": "mpgc_buffalo_skinned", "category": ["animal", "buffalo"]},
    {"name": "Black-tailed Jackrabbits skinned", "key": "mpgc_rabbits_skinned", "category": ["animal", "rabbit"]},
    {"name": "Blackberries picked", "key": "mpgc_black_berry_picked", "category": ["plants", "black_berry"],
             "description": "Go to Mazanita Post, there are some just to the north west of the main building. Then head directly east across the road and into the trees for more."},
    {"name": "Blackcurrants picked", "key": "mpgc_black_currant_picked", "category": ["plants", "black_currant"],
             "description": "Just north of the big mansion in Tumbleweed, there are 3 patches of blackcurrants."},
    {"name": "Blood Money Crimes completed", "key": "mpgc_outlaw_mission_wins", "showgoal": "yes",
             "description": "Anthony Foreman just by Rhodes station is the easiest to get to."},
    {"name": "Bluegill caught", "key": "mpgc_fish_caught_bluegill", "category": ["fish", "bluegill"],
             "description": "Try on the western edge of Saint Denis by the semaphore signal that's just before the railroad bridge."},
    {"name": "Boars skinned", "key": "mpgc_boars_skinned", "category": ["animal", "boar"],
             "description": "You'll often find boars on the road past Harriet at Lagras, just keep following it along the bend to the east.\nThey're in the trees and on the mudflats usually, listen for the squeals.\nBolger Glade, or Black Bone Forest offer good hunting opportunities too."},
    {"name": "Bonnie MacFarlane missions completed", "key": "mpgc_gfh_bonnie_macfarlane_wins", "category": ["gfh", "bonnie"], "showgoal": "yes"},
    {"name": "Bullhead Catfish caught", "key": "mpgc_fish_caught_bullhead_catfish", "category": ["fish", "bullheadcatfish"],
             "description": "Head to Lagras and then go a few metres south to the water by the fishing boat. Use corn for bait."},
    {"name": "Bulls skinned", "key": "mpgc_bulls_skinned", "category": ["animal", "bull_devon"],
             "description": "Found at farms. Try Hill Haven Ranch, north of Rhodes, and east of Mattock Pond. Also at Carmody Dell, northeast of Cornwall Kerosene & Tar. Hanging Dog Ranch at the northwest end of Big Valley also can have them. One can be found in a pen on the road north of Saint Denis, above the 'A' of Bayou Nwa. \nSolo lobbies and switching lobbies to encourage a spawn are recommended. Oxen don't count either."},
    {"name": "Burdock Roots picked", "key": "mpgc_burdock_root_picked", "category": ["plants", "burdock_root"],
             "description": "Just north of Blackwater, at the mouth of the Upper Montana River, on the north bank.\nThere are numerous burdock plants here, you can just keep following the coastline towards the railway bridge for more."},
    {"name": "Camp themes updated", "key": "mpgc_customization_camp_style", "showgoal": "yes"},
    {"name": "Candies eaten", "key": "mpgc_consumable_candy_eaten", "category": ["shops", "general_store"],
             "description": "Peppermints, Candies, and Chocolate Bars all count for this challenge."},
    {"name": "Canned food eaten", "key": "mpgc_consumable_canned_goods_eaten", "category": ["shops", "general_store"]},
    {"name": "Capitale notes collected", "key": "mpgc_capitale_notes_collected",
             "description": "Go to Rhodes and then Anthony Foreman, as the Blood Money Mission, 'The Railroad Contract' is a very\ngood one to find capitale. Part 1 has some in a box at the campsite for example."},
    {"name": "Cats photographed", "key": "mpgc_photograph_cat", "showgoal": "yes"},
    {"name": "Chain Pickerel caught", "key": "mpgc_fish_caught_chain_pickerel", "category": ["fish", "chainpickerel"],
             "description": "Lake Don Julio, or near the fast travel post area of Lagras. Also in the lake by Owanjila Dam.\nTry on the western edge of Saint Denis by the semaphore signal that's just before the railroad bridge.\nAlso at Blackwater in front of the butchers."  },
    {"name": "Channel Catfish caught", "key": "mpgc_fish_caught_channel_catfish", "category": ["fish", "channelcatfish"], "showgoal": "yes",
             "description": "Go to Rhodes and then to the liitle pier on the river just North East of Caliga Hall itself.\nA special swamp lure works well, just be careful they don't swim into the trees to escape."},
    {"name": "Chanterelle picked", "key": "mpgc_chanterelle_picked", "category": ["plants", "chanterelles"],
             "description": "Just to the west of Rhodes station is one patch on the boundary line and near the fallen tree trunks, then ride due west again, almost to the coastline.\nOn the spur of land that sticks out into the lake, there are a couple of patches in the centre of the woods."},
    {"name": "Chickens skinned", "key": "mpgc_chickens_skinned", "category": ["animal", "chicken_leghorn"],
             "description": "Rathskeller Fork, north of Tumbleweed, is the place to get plenty of chickens usually."},
    {"name": "Clothing style updated", "key": "mpgc_customization_clothing_style", "category": ["shops", "tailor"],
             "description": "You can just go to your wardrobe and change outfit for this to register."},
    {"name": "Collared Peccaries skinned", "key": "mpgc_javelina_skinned", "category": ["animal", "javelina"],"showgoal": "yes",
             "description": "These can often be found just north of Ridgewood Farm, north east of Tumbleweed.\nThe hills and valleys around Fort Mercer are a good spot too."},
    {"name": "Common Bulrush picked", "key": "mpgc_common_bulrush_picked", "category": ["plants", "common_bulrush"]},
    {"name": "Complimentary snacks eaten at a Saloon", "key": "mpgc_consumable_saloon_snacks_eaten", "category": ["shops", "saloon"],
             "description": "There are 4 saloons with snacks available. Those are in Blackwater, Valentine, Rhodes and Saint Denis.\nThe Blackwater Saloon has almonds on the far right end of the bar. Smithfields Saloon in Valentine has both almonds and pickled eggs. You can get almonds at the The Rhodes Parlour House, and finally at the Bastile Saloon in Saint Denis too."},
    {"name": "Condors plucked", "key": "mpgc_condor_skinned", "category": ["animal", "californiancondor"],
             "description": "Travel from Armadillo towards Mercer Station especially in the morning, and you'll likely see some overhead. Rio Bravo area, around Fort Mercer and Plainview."},
    {"name": "Cooked Seasoned Big Game", "key": "mpgc_craft_big_game_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cooked Seasoned Crustacean", "key": "mpgc_craft_crustacean_seasoned", "category": ["menu", "campfires"],
             "description": "Crabs can be found on the island west of Rhodes that has the lagoon with the shipwreck. Go to Clemens Point camp and head in a straight line off the old jetty to get there. There may also be some on the banks of the San Luis River, south east of Scratching Post, but those are harder to find.\nUse a bow with small game arrows for best quality."},
    {"name": "Cooked Seasoned Exotic Bird", "key": "mpgc_craft_exotic_bird_seasoned", "category": ["menu", "campfires"],"showgoal": "yes",
             "description": "Pelicans are the best source of Exotic Bird Meat. A good spot is just east of Quaker's Cove.\nAs you come down the road into the cove, to the left is a beach area where they often sit."},
    {"name": "Cooked Seasoned Flaky Fish", "key": "mpgc_craft_flakey_fish_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cooked Seasoned Game", "key": "mpgc_craft_game_seasoned", "category": ["menu", "campfires"],
             "description": "Game is found mainly by killing rabbits, but duck and pheasants work too."},
    {"name": "Cooked Seasoned Mutton", "key": "mpgc_craft_mutton_seasoned", "category": ["menu", "campfires"],
             "description": "Hunt goats, rams or sheep. The easiest way is from the sheep pens at Emerald Ranch."},
    {"name": "Cooked Seasoned Plump Bird", "key": "mpgc_craft_plump_bird_seasoned", "category": ["menu", "campfires"],
             "description": "Chickens and Turkeys give you plump bird meat when plucked. Rathskeller Fork usually has lot of chickens to kill."},
    {"name": "Cooked Seasoned Pork", "key": "mpgc_craft_pork_seasoned", "category": ["menu", "campfires"],
             "description": "Pigs can be found at Flatneck Station in the pens there. Also at the smallholdings all around Valentine, or sometimes in the pens at Armadillo Station. Butchers Creek, Saint Denis market, or the settlement at Braithwaite Manor may also have pigs too." },
    {"name": "Cooked Seasoned Prime Beef", "key": "mpgc_craft_prime_beef_seasoned", "category": ["menu", "campfires"],
             "description": "Beef comes mainly from cows and oxen, but bison will also work."},
    {"name": "Cooked Seasoned Succulent Fish", "key": "mpgc_craft_succulent_fish_seasoned", "category": ["menu", "campfires"],
             "description": "You need trout or salmon for this, breaking them down from your satchel.\nTrout can be found in the San Luis River just south of Scratching Post, around the little island.\nSalmon can be found just below Cumberland Falls."},
    {"name": "Cooked Seasoned Venison", "key": "mpgc_craft_venison_seasoned", "category": ["menu", "campfires"]},
    {"name": "Cormorants plucked", "key": "mpgc_cormorant_skinned", "category": ["animal", "cormorant_doublecrested"],
             "description": "On the Lannahechee River, just east of Catfish Jackson's house is a small bay where a group of comorants can be found on the water. Go into the water on your horse, sneak around them, and fire a shot so they take flight over the land before killing one."},
    {"name": "Cougars killed", "key": "mpgc_cougars_killed", "category": ["animal", "cougar"],
             "description": "Fast travel to Manzanita Post, then head north and take the road to Blackwater. A cougar often attacks around the north entrance of Beecher's Hope. Solo lobbies are far more effective of course."},
    {"name": "Cows skinned", "key": "mpgc_cows_skinned", "category": ["animal", "cow"],
             "description": "Emerald Ranch is the easiest place to find cows, fairly close to the fast travel post."},
    {"name": "Coyotes skinned", "key": "mpgc_coyotes_skinned", "category": ["animal", "coyote"],
             "description": "During the day, circle around Armadillo and you'll probably find some, and at night, around Emerald Ranch, especially south of Joe's hut at 'Osman Grove'"},
    {"name": "Crafted a horse care item", "key": "mpgc_craft_horse_care", "category": ["menu", "campfires"]},
    {"name": "Crafted a Tonic", "key": "mpgc_craft_tonic", "category": ["menu", "campfires"]},
    {"name": "Creeping Thyme picked", "key": "mpgc_creeping_thyme_picked", "category": ["plants", "creeping_thyme"],
             "description": "From MacFarlane's Ranch, go to Harriet's tent. There's a patch just in front of it, and also a couple of patches on the S-Bend in the road nearby."},
    {"name": "Cups of coffee drunk", "key": "mpgc_consumable_coffee_drunk", "category": ["shops", "general_store"],
             "description": "Probably easiest at the moonshine shack, next to the bar."},
    {"name": "Deer skinned", "key": "mpgc_deer_skinned", "category": ["animal", "deer"],
             "description": "Deer are fairly common over most of New Hanover, West Elizabeth and Lemoyne. Scarlett Meadows, Big Valley and to the East of Emerald station are all good spots. Please note that Pronghorns do not count. It has to be Whitetail’s. A Whitetail Buck will count though."},
    {"name": "Defended a campsite", "key": "mpgc_dynamic_campsite_defend", "category": ["menu", "defend_campsite"],
             "description": "Between Macfarlane's Ranch and Armadillo, usually when in a solo lobby, there's a good spot for this."},
    {"name": "Desert Sage picked", "key": "mpgc_desert_sage_picked", "category": ["plants", "desert_sage"],
             "description": "Head south out of Tumbleweed, and at the crossroads next to the 'E' of 'NEW AUSTIN' on the map you'll find the plants."},
    {"name": "Distance driven a train", "key": "mpgc_distance_driven_train", "category": ["menu", "trains"],
             "description": "Fast travel to MacFarlane's Ranch, as a train usually shows up there. Take over the train when in the tunnel to avoid a wanted level. You will complete the distance just as you approach Armadillo too."},
    {"name": "Distance non-player enemy dragged from horseback", "key": "mpgc_lasso_enemy_horseback_dragged",
             "description": "Dragging someone protecting a bounty target is a good way to get this."},
    {"name": "Distance ran", "key": "mpgc_distance_run"},
    {"name": "Distance rowed a boat or canoe", "key": "mpgc_distance_rowed_boat", "category": ["menu", "boats"]},
    {"name": "Distance swam", "key": "mpgc_distance_swim"},
    {"name": "Distance traveled by coach or wagon", "key": "mpgc_distance_coach"},
    {"name": "Distance traveled by train", "key": "mpgc_distance_train", "category": ["menu", "trains"]},
    {"name": "Distance traveled by wagon with a Posse Member", "key": "mpgc_distance_companion_wagon"},
    {"name": "Distance traveled in boat with a Posse Member", "key": "mpgc_distance_companion_boat", "category": ["menu", "boats"],
             "description": "West of Rhodes is Clemens Point camp, you often find canoes and boats travelling past the pier there,\nbetween the coast and the islands. Maybe change sessions, solo lobbies spawn more of them."},
    {"name": "Distance traveled leading own horse", "key": "mpgc_distance_led_horse"},
    {"name": "Distance traveled on a mount with a Posse Member", "key": "mpgc_distance_companion_horse"},
    {"name": "Distance traveled on mount", "key": "mpgc_distance_mount"},
    {"name": "Distance traveled", "key": "mpgc_distance_any"},
    {"name": "Dogs photographed", "key": "mpgc_photograph_dog", "category": ["animal", "dog_street"], "showgoal": "yes"},
    {"name": "Don't reach high Hostility within one game day", "key": "mpgc_notoriety_no_hostility_timed"},
    {"name": "Drinks ordered at a Saloon", "key": "mpgc_consumable_drinks_ordered_saloon", "category": ["shops", "saloon"]},
    {"name": "Dry goods eaten", "key": "mpgc_consumable_dry_goods_eaten", "category": ["shops", "general_store"],
             "description": "Crackers, Bread Rolls, Bread Chunks, and Assorted Biscuits all count towards this."},
    {"name": "Ducks skinned", "key": "mpgc_ducks_skinned", "category": ["animal", "duck_mallard"],
             "description": "At dawn, north east of Emerald Station, there are plenty of ducks around Heartland Overflow."},
    {"name": "Eagles plucked", "key": "mpgc_eagles_skinned", "category": ["animal", "eagle_golden"], "showgoal": "yes",
             "description": "On the cliffs overlooking Scratching Post to the south of Tumbleweed between 9am and 5pm is a good location. Shoot nearby so the eagle takes flight before killing it.\nAlso on the road from Strawberry, just before Owanjila Dam, there is often one on the rock outcrop."},
    {"name": "Egrets skinned", "key": "mpgc_egret_skinned", "category": ["animal", "egret_reddish"], "showgoal": "yes",
             "description": "Ride along the railway line west out of Saint Denis, go over the bridge to the ruined building next to the railway siding. You will often find egrets at the water's edge around there."},
    {"name": "Elk skinned", "key": "mpgc_elk_skinned", "category": ["animal", "elk_rocky"],
             "description": "Set your camp in Big Valley and you'll soon find elk grazing by the winding river.\nTall Trees, north of Manzanita Post is another decent area."},
    {"name": "English Mace picked", "key": "mpgc_english_mace_picked", "category": ["plants", "english_mace"],
             "description": "Head along the path from MacFarlane's Ranch Station up towards Harriet. \nA patch just north of the two abandoned waggons, and then more along the roadside towards Harriet."},
    {"name": "Escaped the law", "key": "mpgc_law_lose_wanted"},
    {"name": "Evergreen Huckleberries picked", "key": "mpgc_evergreen_huckleberry_picked", "category": ["plants", "evergreen_huckleberry"],
             "description": "Fast travel to Lagras and head towards Harriet. Just past her tent, on the left of the road are a couple of bushes, then follow the road past the junction and around the bend to find more plants either side of the road, between the 'M' and 'R' of 'MARSH' on the map."},
    {"name": "Facial appearance updated at a Barber", "key": "mpgc_customization_facial_appearance", "category": ["shops", "barber"]},
    {"name": "Feathers sold", "key": "mpgc_shop_feathers_sell", "category": ["shops", "butcher"],
             "description": "Blackwater, Rhodes, Tumbleweed, Valentine, Saint Denis, and Strawberry all have butchers.\nGus will also buy feathers."},
    {"name": "Finish a mode in Featured Series", "key": "mpgc_series_featured_attempts"},
    {"name": "Finish Race in Race Series", "key": "mpgc_series_race_attempts"},
    {"name": "Finish Showdown in any Showdown Series", "key": "mpgc_series_adversarial_attempts",
             "description": "Featured Series does not count for this.\nShootout Series is the best bet, but be in the lobby at the start for it to count."},
    {"name": "Finish Showdown in Elimination Series", "key": "mpgc_series_elimination_attempts"},
    {"name": "Finish Showdown in Shootout Series", "key": "mpgc_series_shootout_attempts"},
    {"name": "Finish Showdown in Takeover Series", "key": "mpgc_series_takeover_attempts"},
    {"name": "Fish caught weighing at least 5 lbs (2.2 kg)", "key": "mpgc_fish_size_caught", "category": ["shops", "tackle"],
             "description": "At Blackwater, you can find massive Lake Sturgeon in the lake just in front of the tailors shop and butchers."},
    {"name": "Fish caught with a lure", "key": "mpgc_fish_caught_lure", "category": ["shops", "tackle"],
             "description": "The special spinner works for this challenge as well."},
    {"name": "Fish caught with food", "key": "mpgc_fish_caught_food", "category": ["shops", "tackle"]},
    {"name": "Fish caught with live bait", "key": "mpgc_fish_caught_live_bait", "category": ["shops", "tackle"]},
    {"name": "Fish caught", "key": "mpgc_fish_caught", "category": ["shops", "tackle"],
             "description": "Around the small island in the San Luis River just south of Scratching Post is a great place to fish."},
    {"name": "Flying birds killed while on a moving train", "key": "mpgc_flying_bird_train_kills"},
    {"name": "Flying birds killed with a sniper rifle", "key": "mpgc_flying_bird_kills_sniper"},
    {"name": "Flying birds killed", "key": "mpgc_flying_bird_kills",
             "description": "Big Valley is a good location to find lots of birds for this challenge."},
    {"name": "Followed dog to something interesting", "key": "mpgc_dynamic_hobo_dog", "category": ["menu", "dog_encounter"],
             "description": "This one is difficult to find. Sometimes there is one just south of Armadillo near Old Man Jones when doing a moonshine delivery. Solo lobbies more likely as well of course. "},
    {"name": "Foxes skinned", "key": "mpgc_foxes_skinned", "category": ["animal", "fox_red"],
             "description": "A good spot with a regular spawn is just north east of Emerald Station. Follow the railway line around the S-bend in the track, and you'll normally find one a few feet from the railway, by the T-Junction and the track to the little shack."},
    {"name": "Free Roam Events played", "key": "mpgc_fme_attempts"},
    {"name": "Free Roam missions completed", "key": "mpgc_gfh_wins",
             "description": "Look for the orange disc with the waving figure in it on the map.\nCaravan Escort missions don't seem to register.\nFree Roam missions are given out by Alden, Angus, Bonnie MacFarlane, Hector, Hamish Sinclair, Jake & Sadie Adler, Thomas, Sheriff Freeman, Anthony Foreman, Josiah Trelawny, Sean MacGuire, The Boy, Flaco Hernandez, Bray and Tammy Aberdeen, Black Belle, Mama Watson, James Langton, and Shaky."},
    {"name": "Fresh produce eaten", "key": "mpgc_consumable_fresh_produce_eaten", "category": ["shops", "general_store"],
             "description": "Apples, Pears, Carrots, Peaches, Beets and Corn should all count for this one. Things like berries and mushrooms don't work."},
    {"name": "Geese skinned", "key": "mpgc_goose_skinned", "category": ["animal", "goosecanada"],
             "description": "Head to Heartland Overflow by Emerald Ranch, and just below the letter 'r' in 'Overflow' there are some trees where you can usually find a flock of resting geese. You can kill 5 or 6 as they take flight. Lobby swap until they spawn. Early morning is a good time to try this."},
    {"name": "Go On-Call and complete a Story mission", "key": "mpgc_story_mission_wins_on_call",
             "description": "Left Menu, then Quick Join and then Story Mission On-Call to start a Land Of Opportunities story mission."},
    {"name": "Golden Currants picked", "key": "mpgc_golden_currant_picked", "category": ["plants", "golden_currant"],
             "description": "Head out of Blackwater on the road west by the stables, and you'll find the Great Plains are full of plants.\nThere's a couple of bushes full of golden currents below the 'A' in Blackwater on the map, just below the 'Broken Tree' writing, and another couple just under the tree itself.", },
    {"name": "Hairstyle updated", "key": "mpgc_customization_hairstyle", "category": ["shops", "barber"]},
    {"name": "Hamish Sinclair missions completed", "key": "mpgc_gfh_hamish_sinclair_wins", "category": ["gfh", "war_vet"], "showgoal": "yes"},
    {"name": "Hawks plucked", "key": "mpgc_hawks_skinned", "category": ["animal", "hawk_ferruginous"], "showgoal": "yes",
             "description": "Rathskeller Fork often has a hawk on the roof of the western building."},
    {"name": "Helped someone in need", "key": "mpgc_dynamic_rescue_escort_ped", "category": ["menu", "rescue"],
             "description": "At Colter in an empty lobby you'll often rescue a woman who needs to go to Adler Ranch.\nJust above the 'S' in Saint Denis is often the start of a rescue mission, as is just below the 'D' in Denis.\nOn the road out of Blackwater before Quakers Cove there's often a woman offering a rescue."},
    {"name": "Herb Picking Contest completed", "key": "mpgc_posse_herb_challenge_completed"},
    {"name": "Herbs eaten", "key": "mpgc_consumable_herbs_tasted", "category": ["shops", "doctor"],
             "description": "Oregano, Wild Carrot, Parasol Mushrooms do count.\nFruits such as Golden currents maybe don't count, neither does Ginseng.\nSeems bugged, multiple items of the same type don't always register. 2 from the same patch often don't register more than one." },
    {"name": "Herbs sold", "key": "mpgc_shop_herbs_sell", "category": ["shops", "doctor"],
             "description": "Go to the doctor in Valentine or Saint Denis, and sell some herbs."},
    {"name": "Herons skinned", "key": "mpgc_herons_skinned", "category": ["animal", "heron_greatblue"],
             "description": "South of Black Belle's Canebreak Manor in Bluewater Marsh you can usually find plenty. The marshes are full of them normally, especially in the east around the railway lines.\nNorth West of Rhodes, the bay just below Clemens Point camp often has a number of herons."},
    {"name": "Hideouts cleared", "key": "mpgc_hideout_clear", "category": ["menu", "hideouts"],
             "description": "Can be tricky as they don't spawn very often. A solo lobby will help.\nHanging Dog Ranch at the west end of Big Valley seems more common than some." },
    {"name": "Horse appearance updated", "key": "mpgc_customization_horse_style", "category": ["shops", "stable"],
             "description": "You don't have to change your current horse, any of your stable will register.\nTry changing a tail or mane, using one of the free options."},
    {"name": "Horse tack updated", "key": "mpgc_customization_horse_kit", "category": ["shops", "stable"],
             "description": "At any stable, select Horses, then Tack and Services, then Saddles, and pick your existing ticked saddle.\nThat should trigger the challenge, you don't need to alter anything."},
    {"name": "Horse tonics used", "key": "mpgc_horse_tonics_given"},
    {"name": "Horses fed", "key": "mpgc_horse_fed"},
    {"name": "Hummingbird Sage picked", "key": "mpgc_hummingbird_sage_picked", "category": ["plants", "hummingbird_sage"],
             "description": "Head north from Manzanita Post until you get to the little triangular junction. There are a few patches just in the trees north of there."},
    {"name": "Hunt the Leader completed", "key": "mpgc_posse_hunt_posse_leader_attempts"},
    {"name": "Iguanas skinned", "key": "mpgc_iguanas_skinned", "category": ["animal", "iguanadesert"],
             "description": "The little island in the San Luis River, just south of Scratching Post often has iguanas."},
    {"name": "Indian Tobacco picked", "key": "mpgc_indian_tobacco_picked", "category": ["plants", "indian_tobacco"],
             "description": "Fast travel to Rhodes, ride north and cross the railway line at the big red barn.\nOn your left are a few patches of Indian Tobbaco near to the left side of the road."},
    {"name": "Items sold to a Fence", "key": "mpgc_shop_sell_to_fence", "category": ["shops", "fence",],
             "description": "Emerald Ranch, Rhodes, Thieves Landing and Saint Denis market all have a Fence."},
    {"name": "Items sold to Gus", "key": "mpgc_shop_sell_to_trapper", "category": ["shops", "trapper"],
             "description": "Beaver Teeth and Wolf Hearts are a good thing to sell, as Cripps can't use those for trader role."},
    {"name": "James Langton missions completed", "key": "mpgc_gfh_james_langton_wins", "category": ["gfh", "langton"], "showgoal": "yes"},
    {"name": "Joe missions completed", "key": "mpgc_gfh_joe_wins", "category": ["gfh", "joe"], "showgoal": "yes"},
    {"name": "Jumped from a horse onto a moving train", "key": "mpgc_horse_jump_to_train", "category": ["menu", "trains"]},
    {"name": "Jumped from a horse to a moving wagon", "key": "mpgc_horse_jump_to_wagon"},
    {"name": "Jumped from a horse to another horse", "key": "mpgc_horse_jump_to_horse"},
    {"name": "Jumped onto a horse from a 3m height", "key": "mpgc_horse_jump_from_height", "showgoal": "no",
             "description": "Go to Blackwater and climb the first ladder at the back of the musical theatre, then jump on to your horse below."},
    {"name": "Lake Sturgeon caught", "key": "mpgc_fish_caught_lake_sturgeon", "category": ["fish", "lake_sturgeon"],
             "description": "A great spot is in front of the lakeside shops in Blackwater, usually a couple there.\nChange lobby if they're not biting."},
    {"name": "Largemouth Bass caught", "key": "mpgc_fish_caught_largemouth_bass", "category": ["fish", "largemouthbass"]},
    {"name": "Little Brown Bats collected", "key": "mpgc_bats_skinned", "category": ["animal", "bat"],
             "description": "The cave behind the waterfall at Elysian Pool, at night is probably the best spot.\nSwitch lobbies to get them to spawn if none there."},
    {"name": "Longnose Gar caught", "key": "mpgc_fish_caught_longnose_gar", "category": ["fish", "longnosegar"]},
    {"name": "Loons skinned", "key": "mpgc_loon_skinned", "category": ["animal", "loon_pacific"],
             "description": "From Blackwater, head to the river crossing above the 'A' in the West Elizabeth text on the map. There's usually one in the water, during the day of course.",
             "description2": "At the north east corner of Owanjila, close to the shore where the road turns down to the dam, there are often a couple of loons swimming in shallow water during the day."},
    {"name": "Masks worn", "key": "mpgc_customization_mask", "category": ["shops", "tailor"],
             "description": "Madam Nazar sells various masks if you don't one already."},
    {"name": "Meats eaten", "key": "mpgc_consumable_meat_eaten", "category": ["shops", "butcher"]},
    {"name": "Milkweed picked", "key": "mpgc_milkweed_picked", "category": ["plants", "milkweed"],
             "description": "Head to Lagras and follow the road north past Harriet. There's a few patches below 'MAR' in Marsh on the map.",
             "description2": "Go to Rhodes, then a little north to either Southfield Flats or Mattock Pond to find plenty of Milkweed.",
             "description3": "From Emerald Station, head north west to find plenty around the water at Heartlands Overflow, or along the creek that runs to the west of Emerald Ranch." },
    {"name": "Moose skinned", "key": "mpgc_moose_skinned", "category": ["animal", "moose"]},
    {"name": "Multiple Player kills in 5 sec. in Free Roam Events", "key": "mpgc_players_killed_fme_timer",
             "description": "Fools Gold, Railroad Baron, Cold Dead Hands, and King Of The Castle are good choices for this.\nMaybe a well aimed dynamite arrow at the Railroad Baron spawn area is the best way to get them in a single shot."},
    {"name": "Multiple Player kills in 5 seconds in Posse Versus", "key": "mpgc_players_killed_pv_timer"},
    {"name": "Multiple Player kills in 5 seconds in Showdowns", "key": "mpgc_players_killed_showdown_timer"},
    {"name": "Muskie caught", "key": "mpgc_fish_caught_muskie", "category": ["fish", "muskie_clear"],
             "description": "Ride west out of Strawberry to Owanjilla. \nRide all the way along the shore of the lake to the very western end where the little waterfall is. \nThis is a great spot to fish for Muskies. You will need a lure or a spinner to target these larger fish."},
    {"name": "Nine-banded Armadillos skinned", "key": "mpgc_armadillo_skinned", "category": ["animal", "armadillo"],
             "description": "Best hunted after dark, the area around Armadillo, such as north of the stable pens, is a good place.\nAlso around Mercer Station."},
    {"name": "Non-player enemies grappled to the ground", "key": "mpgc_enemies_grappled_to_ground",
             "description": "Go brawling with the Del Lobos at Thieves Landing."},
    {"name": "Non-player enemies killed at long range", "key": "mpgc_enemies_killed_from_long_distance",
             "description": "Del Lobo's at Thieves Landing, or Revenue Agents at a roadblock are good targets, as are trader resupply NPC's. Use a scoped rifle or maybe a bow with dead eye for the distance.\nYou should see a popup notification on the right of the screen if it counts.\nTrade Route with a repeater is good for this as well."},
    {"name": "Non-player enemies killed from cover", "key": "mpgc_enemies_killed_cover",
             "description": "Go to Thieves Landing and kill Del Lobos. You can use the trees on the approach to hide behind."},
    {"name": "Non-player enemies killed from the hip", "key": "mpgc_enemies_killed_from_hip"},
    {"name": "Non-player enemies killed while in Dead Eye", "key": "mpgc_enemies_killed_deadeye",
             "description": "Trade Route is rather good for this challenge."},
    {"name": "Non-player enemies killed while not seen", "key": "mpgc_enemies_killed_stealth",
             "description": "Use a bow. There are a couple of men by the stable at Thieves Landing. Approach from Blackwater.\nFire at them from near the bridge, a headshot with Dead Eye is the aim. Only one will count as stealth.\nThen retreat back over the bridge to reset their spawn point. Repeat."},
    {"name": "Non-player enemies killed with a Maxim Gun", "key": "mpgc_enemies_killed_gatling_maxim", "category": ["menu", "hideouts"],
             "description": "The moonshiner story mission 'The Certainty Of Death and Taxes' has one after the flames.\nThe Land of Opportunities mission 'Kerosene, Tar, and Greed' has 2 Maxim Guns on the train,\nor 'Kill Them, Each and Every One' at Fort Mercer. Or gang hideouts."},
    {"name": "Non-player enemies knocked out", "key": "mpgc_enemies_knocked_out",
             "description": "Go brawling with the Del Lobos at Thieves Landing."},
    {"name": "Non-player enemies lassoed from horseback", "key": "mpgc_lasso_enemy_horseback"},
    {"name": "Non-player enemies looted", "key": "mpgc_enemies_looted"},
    {"name": "Non-player enemies trampled", "key": "mpgc_horse_enemies_trampled",
             "description": "Thieves Landing NPCs are probably the easiest way to complete this, or try enemies in bounty missions or resupply missions. They have to be Del Lobos or red enemies on the mini-map to count."},
    {"name": "Non-player enemy hats shot off", "key": "mpgc_enemy_hats_shot_off",
             "description": "Moonshiner roadblocks with a varmint rifle at a distance, or get a wanted level and fend off the law."},
    {"name": "North American Raccoons skinned", "key": "mpgc_raccoons_skinned", "category": ["animal", "racoon"]},
    {"name": "Northern Pike caught", "key": "mpgc_fish_northern_pike", "category": ["fish", "northernpike"]},
    {"name": "Oleander Sage picked", "key": "mpgc_oleander_picked", "category": ["plants", "oleander_sage"],
             "description": "At Lagras, there's a patch in the trees by the road just near Harriet, and there's more just north of that.\nIt's inside the horseshoe curve in the road, between the letters 'L' and 'M' on the map.\nFurther on too, just below 'A' and 'R' on the map there's a patch either side of the road."},
    {"name": "Oregano picked", "key": "mpgc_oregano_picked", "category": ["plants", "oregano"],
             "description": "Head south out of Blackwater, and just past the first house on the left, near the city boundary, you'll find a few patches of Oregano."},
    {"name": "Other players photographed", "key": "mpgc_photograph_player", "showgoal": "yes"},
    {"name": "Owls plucked", "key": "mpgc_owls_skinned", "category": ["animal", "owl_great"], "showgoal": "yes",
             "description": "Very difficult. In Tall Trees at Tanner's Reach they often perch around Sean's hut or the little cliff above it. Try swapping lobbies a lot. Dusk and dawn seem to improve chances, rather than at night."},
    {"name": "Oxen skinned", "key": "mpgc_oxen_skinned", "category": ["animal", "ox_angus"],
             "description": "Emerald Ranch usually has oxen, you can always head south and past the farm boundary, then return to get a fresh spawn. Guthrie Farm just to the northwest also usually has one.\nLasso and kill them with a knife to reduce the chances of an alarm being raised for animal cruelty."},
    {"name": "Panthers killed", "key": "mpgc_panthers_killed", "category": ["animal", "panther"],
     "description": "Near Braithwaite Manor, in the woods to the south by Black Belle's hideout is a good place.\nYou have to hunt at night though"},
    {"name": "Parasol Mushrooms picked", "key": "mpgc_parasol_mushroom_picked", "category": ["plants", "parasol_mushroom"],
             "description": "Head south along the railway line out of Valentine until you get to the big crossroads, plenty just east of there. Also the pig pens at Flatneck Station have some.\nGo South out of Blackwater, and just past the first house on the left there's some, next to the boundary line on the map.\nIn front of Harriet's tent at MacFarlane's Ranch has some too."},
    {"name": "Pelicans plucked", "key": "mpgc_pelicans_skinned", "category": ["animal", "pelican_white"]},
    {"name": "Perch caught", "key": "mpgc_fish_caught_perch", "category": ["fish", "perch"],
             "description": "Found in most Northern lakes and rivers. Bread or a special spinner for bait, and wait for sunny weather. \nA good spot is the pond in front of the abandoned sect building north of Emerald Station."},
    {"name": "Perfect pelts sold", "key": "mpgc_shop_pelt_pristine_sell", "category": ["shops", "butcher"],
             "description": "Looted pelts from NPC's are a good thing to have in your satchel, keep them for this challenge.\nSheep pelts are quite easy to get at Emerald Ranch, an arrow to the head keeps the quality.\nHas to be pelts, so animal carcasses don't count."},
    {"name": "Petted a dog", "key": "mpgc_dog_pat", "category": ["animal", "dog_street"],
             "description": "Your camp dog is the easiest way to get this, or try Armadilo by the undertakers, and maybe Tumbleweed around the butchers."},
    {"name": "Pheasants skinned", "key": "mpgc_pheasants_skinned", "category": ["animal", "pheasant_ringneck"],
             "description": "Just south east of Valentine, by the turn off to the serial killers cabin is a great spot next to the road.\nLook in the trees on the D-shaped bit of land where the path curves under the road.\nAlso, east of the southern road out of Blackwater by the boundary line."},
    {"name": "Photographed your horse", "key": "mpgc_photograph_your_horse"},
    {"name": "Pigs skinned", "key": "mpgc_pigs_skinned", "category": ["animal", "pig_berkshire"],
             "description": "Flatneck Station is probably the easiest place for this."},
    {"name": "Placed top 3 in a Race", "key": "mpgc_race_wins"},
    {"name": "Placed top 3 in a Shootout Showdown", "key": "mpgc_series_shootout_wins",
             "description": "Can be tricky to get a match for this, but Public Enemy is the easiest one to get this with, as you just need to be on the winning team. You'll need to be in the lobby at the start for it to count though."},
    {"name": "Placed top 3 in a Showdown", "key": "mpgc_showdown_wins"},
    {"name": "Placed top 3 in a Takeover Showdown", "key": "mpgc_series_takeover_wins",
             "description": "Can be tricky to get matchmaking for this, but keep trying."},
    {"name": "Placed top 3 in an Elimination Showdown", "key": "mpgc_series_elimination_wins"},
    {"name": "Placed top 3 with a score in Free Roam Events", "key": "mpgc_fme_wins",
             "description": "Something like Manhunt is a good one to try, low numbers and a low bar for success. Trade Route is another, Wildlife Photographer too. Basically, just keep playing Free Roam events."},
    {"name": "Player headshot kills in Free Roam Events", "key": "mpgc_players_headshot_fme", "showgoal": "yes",
             "description": "King Of The Castle, Cold Dead Hands, Railroad Baron, and Fools Gold are probably the best option."},
    {"name": "Player headshot kills in Posse Versus", "key": "mpgc_players_headshot_pv", "showgoal": "yes"},
    {"name": "Player headshot kills in Showdowns", "key": "mpgc_players_headshot_showdown", "showgoal": "yes"},
    {"name": "Player kills from cover in Free Roam Events", "key": "mpgc_players_cover_fme", "showgoal": "yes"},
    {"name": "Player kills from cover in Showdowns", "key": "mpgc_players_cover_showdown", "showgoal": "yes"},
    {"name": "Player kills from the hip in Free Roam Events", "key": "mpgc_players_killed_from_hip_fme", "showgoal": "yes",
             "description": "Revolvers fired without aiming first seem a good way, you can fire repeatedly very quickly.\nCold Dead Hands and King Of The Castle are the best bet for completion."},
    {"name": "Player kills from the hip in Showdowns", "key": "mpgc_players_killed_from_hip_showdown", "showgoal": "yes"},
    {"name": "Player kills in Dead Eye in Free Roam Events", "key": "mpgc_players_deadeye_fme", "showgoal": "yes"},
    {"name": "Player kills in Dead Eye in Showdowns", "key": "mpgc_players_deadeye_showdown", "showgoal": "yes"},
    {"name": "Player kills in Free Roam Events", "key": "mpgc_players_killed_fme", "showgoal": "yes",
             "description": "Cold Dead Hands, King Of The Castle, Fools Gold and of course Railroad Baron are the best ones to try."},
    {"name": "Player kills in Posse Versus", "key": "mpgc_players_killed_pv", "showgoal": "yes"},
    {"name": "Player kills in Showdowns", "key": "mpgc_players_killed_showdown", "showgoal": "yes",
             "description": "Featured series does count if you start in the lobby, but usually free aim so harder."},
    {"name": "Player kills with a Bow in Free Roam Events", "key": "mpgc_players_killed_bow_fme", "showgoal": "yes"},
    {"name": "Player kills with a Bow in Showdowns", "key": "mpgc_players_killed_bow_showdown", "showgoal": "yes"},
    {"name": "Player kills with a Pistol in Free Roam Events", "key": "mpgc_players_killed_pistol_fme", "showgoal": "yes"},
    {"name": "Player kills with a Pistol in Showdowns", "key": "mpgc_players_killed_pistol_showdown", "showgoal": "yes"},
    {"name": "Player kills with a Repeater in Free Roam Events", "key": "mpgc_players_killed_repeater_fme", "showgoal": "yes",
             "description": "Cold Dead Hands, Railroad Baron, Fools Gold, and King of the Castle are probably the best option."},
    {"name": "Player kills with a Repeater in Showdowns", "key": "mpgc_players_killed_repeater_showdown", "showgoal": "yes"},
    {"name": "Player kills with a Revolver in Free Roam Events", "key": "mpgc_players_killed_revolver_fme", "showgoal": "yes"},
    {"name": "Player kills with a Revolver in Showdowns", "key": "mpgc_players_killed_revolver_showdown", "showgoal": "yes"},
    {"name": "Player kills with a Rifle in Free Roam Events", "key": "mpgc_players_killed_rifle_fme", "showgoal": "yes"},
    {"name": "Player kills with a Rifle in Showdowns", "key": "mpgc_players_killed_rifle_showdown", "showgoal": "yes"},
    {"name": "Player kills with a Shotgun in Free Roam Events", "key": "mpgc_players_killed_shotgun_fme", "showgoal": "yes"},
    {"name": "Player kills with a Shotgun in Showdowns", "key": "mpgc_players_killed_shotgun_showdown", "showgoal": "yes"},
    {"name": "Player kills with explosives in Free Roam Events", "key": "mpgc_players_killed_explosives_fme", "showgoal": "yes",
             "description": "Explosive ammo or dynamite arrows.\nRailroad Baron is a good one, but King Of The Castle, Cold Dead Hands, or Fools Gold will also do."},
    {"name": "Player kills with explosives in Showdowns", "key": "mpgc_players_killed_explosives_showdown", "showgoal": "yes",
             "description": "Dynamite Arrows and Dead Eye are the easiest way to get this. You can use explosive ammo too.\nUsually need to have been in the lobby for kills to register."},
    {"name": "Player kills with melee in Free Roam Events", "key": "mpgc_players_killed_melee_fme", "showgoal": "yes",
             "description": "Stamina tonics, then knock down and subdue players."},
    {"name": "Player kills with melee in Showdowns", "key": "mpgc_players_killed_melee_showdown", "showgoal": "yes"},
    {"name": "Player kills with throwing weapons in Showdowns", "key": "mpgc_players_killed_throw_showdown", "showgoal": "yes",
             "description": "Dynamite, tomahawks and hatchets in regular Shootouts or Featured Series, and you can often get tomahawks and throwing knives in Elimination Series.\nStill quite a tricky one though."},
    {"name": "Player kills with thrown weapons in Free Roam Events", "key": "mpgc_players_killed_throw_fme", "showgoal": "yes",
             "description": "Cold Dead Hands, King Of The Castle, Fools Gold or Railroad Baron are the best events to try this in.\nThrowing knives or tomahawks, together with Dead Eye headshots are a good idea, though dynamite should also work but it's harder to kill with."},
    {"name": "Player stats boosted by tonics", "key": "mpgc_consumable_tonics_oils_used", "category": ["shops", "general_store"], "showgoal": "yes"},
    {"name": "Players headshot with a Bow in Free Roam Events", "key": "mpgc_players_headshot_bow_fme", "showgoal": "yes"},
    {"name": "Players headshot with a Bow in Showdowns", "key": "mpgc_players_headshot_bow_showdown", "showgoal": "yes"},
    {"name": "Players revived", "key": "mpgc_players_revived", "showgoal": "yes",
             "description": "Go into a posse with someone, turn on friendly fire, shoot them in the knee with a Varmint Rifle using\nregular ammo until downed. Revive them, then repeat until you’re finished."},
    {"name": "Posse Infighting completed", "key": "mpgc_posse_infighting_completed"},
    {"name": "Posse Races completed", "key": "mpgc_posse_race_attempts"},
    {"name": "Posses joined", "key": "mpgc_posse_join", "showgoal": "yes"},
    {"name": "Prairie Chickens skinned", "key": "mpgc_prairiechicken_skinned", "category": ["animal", "prairiechicken"],
             "description": "Where the road from Cornwall Kerosene and Tar joins the road at Twin Stack Pass is a great place, there are spawn points at the junction where all the roads meet, near the 'W' of 'NEW HANOVER' on the map."},
    {"name": "Prairie Poppies picked", "key": "mpgc_prairie_poppy_picked", "category": ["plants", "prairie_poppy"],
             "description": "Head south out of Blackwater, and just past the first house on the east side, follow the boundary line and you'll find a couple of patches. There are another couple just south of this too, all within walking distance."},
    {"name": "Pronghorns skinned", "key": "mpgc_pronghorns_skinned", "category": ["animal", "pronghorn_american_m"],
             "description": "The western end of Big Valley, just north of the 'W' in 'West Elizabeth' is a great hunting location.\nA solo lobby will help with the spawns."},
    {"name": "Provisions cooked at campfires", "key": "mpgc_craft_food", "category": ["menu", "campfires"]},
    {"name": "Put a mask on your horse", "key": "mpgc_customization_horse_mask", "category": ["shops", "stable"]},
    {"name": "Ram's Head picked", "key": "mpgc_rams_head_picked", "category": ["plants", "rams_head"],
             "description": "Go to Cumberland Forest, just below the letter ‘C’ at the beginning of the word Cumberland on the map.\nWalk in a straight line from the Six Point Cabin path to find one, then go north, near a dark grey rock. There is another patch where the letter ‘M’ is too."},
    {"name": "Rams skinned", "key": "mpgc_rams_skinned", "category": ["animal", "bighornram_desert"],
             "description": "Can be difficult. South of Tumbleweed, look near the letter E in New Austin on the map.\nAnother good spot to try is the north-west end of Big Valley, past the house on stilts.\nCattail Pond, west of Valentine, is also a good spot to find them."},
    {"name": "Raspberries picked", "key": "mpgc_red_raspberry_picked", "category": ["plants", "red_raspberry"],
             "description": "Fast travel to Emerald Station and then head southwest. There's a bush by the bridge near the sheep pens, and then further on by the two junctions there are more bushes to be found.\nIf you need more, try all around the edge of the water at Heartland Overflow.",
             "description2": "Head out of Valentine by the railway station and there are bushes just to the south east, and also just to the east of the tracks at the railway station."},
    {"name": "Rats collected", "key": "mpgc_rats_skinned", "category": ["animal", "rat_black"],
             "description": "The cave behind the waterfall at Elysian Pool is where to go, change lobbies if you need more.\nQuite a lot at Van Horn behind the bar, or go south to the shack at the end of Copperhead Landing.\nPrinz & Co west of Saint Denis is a decent spot too."},
    {"name": "Red Sage picked", "key": "mpgc_red_sage_picked", "category": ["plants", "red_sage"],
             "description": "Ride south out of Armadillo, crossing the railroad twice. Opposite Two Crows near the old waggon\nthere are 3 patches spread either side of the road."},
    {"name": "Redfin Pickerel caught", "key": "mpgc_fish_caught_redfin_pickerel", "category": ["fish", "redfinpickerel"],
             "description": "Fast travel to Blackwater, and just north of the town hall building is a little bay at the mouth of the Upper Montana River. This is the place to catch them.\nA sunny day is best, with bread bait or a special spinner."},
    {"name": "Rock Bass caught", "key": "mpgc_fish_caught_rock_bass", "category": ["fish", "rockbass"],
             "description": "Fast travel to Blackwater and fish from the wooden slipway under construction, where it slopes down\nto the water. Lake Don Julio is another decent spot."},
    {"name": "Roosters skinned", "key": "mpgc_roosters_skinned", "category": ["animal", "rooster_dominique"],
             "description": "There's usually a rooster at Mama Watson's Cabin in Big Valley. There might be some in Strawberry,\nor try the auction yard in Valentine. Another spot is around the fast travel post in Lagras.\nAlso try Emerald Ranch, or maybe the little communities at Rhodes or Braithwaite Manor."},
    {"name": "Sadie Adler missions completed", "key": "mpgc_gfh_sadie_adler_wins", "category": ["gfh", "sadie_adler"], "showgoal": "yes"},
    {"name": "Seagulls plucked", "key": "mpgc_seagulls_skinned", "category": ["animal", "seagull_herring"],
             "description": "A good location is the little spit of land at the south east corner of Blackwater, level with 'Flat Iron' on the map. You can also find them north of the town, along the mouth of the Upper Montana river.\nOften some on the piers at Thieves Landing too, or try Annesburg and Van Horn coastlines. The rocks south of Van Horn lighthorse often have plenty"},
    {"name": "Sean Macguire missions completed", "key": "mpgc_gfh_sean_macquire_wins", "category": ["gfh", "sean_macquire"], "showgoal": "yes"},
    {"name": "Self portraits taken", "key": "mpgc_photograph_selfie"},
    {"name": "Shaky missions completed", "key": "mpgc_gfh_shaky_wins", "category": ["gfh", "shaky"], "showgoal": "yes",
             "description": "Thieves Landing, or west of Armadillo near the Pleasance House, or on the San Luis River, east of\nScratching Post. Maybe use a Change Appearance solo lobby to prevent registration issues."},
    {"name": "Sheep skinned", "key": "mpgc_sheep_skinned", "category": ["animal", "sheep"],
             "description": "Emerald Ranch at night is the best place. You can lasso them and use a knife, or kill with a bow and arrow to remain stealthy."},
    {"name": "Small animal carcasses broken down", "key": "mpgc_craft_broke_down_small_animals",
             "description": "Easiest method here is to open your satchel, select the ingredients tab and then break down fish."},
    {"name": "Small bird carcasses collected", "key": "mpgc_songbirds_collected"},
    {"name": "Smallmouth Bass caught", "key": "mpgc_fish_caught_smallmouth_bass", "category": ["fish", "smallmouthbass"],
             "description": "From Rhodes, head west to Clemens Point campsite, and fish from the old pier.\nAnother spot is just south of Strawberry, between the two river crossings on the Upper Montana."},
    {"name": "Snakes skinned", "key": "mpgc_snakes_skinned", "category": ["animal", "snake"],
             "description": "Past the large wooden plank bridge by the Sea Of Corrado, New Austin, in the middle of the U-Bend."},
    {"name": "Sockeye Salmon caught", "key": "mpgc_fish_caught_sockeye_salmon", "category": ["fish", "salmon_sockeye"],
             "description": "Go to Cumberland Falls, west of Valentine, and fish in the pool below the falls. Usually a few Salmon in there to catch."},
    {"name": "Spoonbills skinned", "key": "mpgc_spoonbill_skinned", "category": ["animal", "roseatespoonbill"]},
    {"name": "Squirrels collected", "key": "mpgc_squirrel_skinned", "category": ["animal", "squirrel_grey"],
             "description": "Common in wooded areas, so around Manzanita Post is a good spot, maybe Rhodes or Strawberry.\nAt the entrace to the Braithwaite Manor driveway, to the west of Radley's Pasture is a great area too."},
    {"name": "Steelhead Trout caught", "key": "mpgc_fish_caught_steelhead_trout", "category": ["fish", "steelheadtrout"],
             "description": "The little lagoon and island in the San Luis river, just south of Scratching Post is a great spot to find Steelhead Trout."},
    {"name": "Stopped a runaway wagon", "key": "mpgc_dynamic_runaway_wagon", "category": ["menu", "runaway_wagon"]},
    {"name": "Striped Skunks skinned", "key": "mpgc_skunks_skinned", "category": ["animal", "skunk"],
             "description": "At night, around Riggs Station and usually just along the road heading north.\nBolger Glade battlefield has a few, also around Cumberland Forest."},
    {"name": "Successfully fended off an ambush", "key": "mpgc_dynamic_ambush", "category": ["menu", "ambush"]},
    {"name": "Telegram missions completed", "key": "mpgc_telegram_mission_wins", "showgoal": "yes"},
    {"name": "The Boy missions completed", "key": "mpgc_gfh_the_boy_wins", "category": ["gfh", "the_boy"], "showgoal": "yes"},
    {"name": "Times became drunk", "key": "mpgc_consumable_became_drunk", "category": ["shops", "saloon"], "showgoal": "yes"},
    {"name": "Tobacco smoked or chewed", "key": "mpgc_consumable_tobacco_used", "category": ["shops", "general_store"]},
    {"name": "Train clerk missions completed", "key": "mpgc_gfh_train_clerk_wins", "category": ["gfh", "wallace_train_clerk"], "showgoal": "yes",
             "description": "He can be found at either Emerald Station, Saint Denis Station or Wallace Station near Big Valley."},
    {"name": "Treasure Maps or treasures found", "key": "mpgc_dynamic_found_treasure_or_map", "category": ["menu", "tree_map"], "showgoal": "yes",
             "description": "Much easier to use an existing treasure map to find some treasure, than it is to search bodies or find one pinned to a tree. Get one every time you gain 5 levels."},
    {"name": "Turkeys skinned", "key": "mpgc_turkeys_skinned", "category": ["animal", "turkey_eastern"],
             "description": "The western end of Big Valley where the two roads meet is a good hunting location.\nThere should be plenty just south of Butcher Creek and Elysian Pool, and also around Rhodes, and there's often some in the triangle of railway lines just north of Emerald Station."},
    {"name": "Turtles skinned", "key": "mpgc_turtle_skinned", "category": ["animal", "turtle_snapping"], "showgoal": "yes",
             "description": "South of Saint Denis, in the marshy inlets by Crawdad Willie's shack. Nearly always one around there.\nBluewater Marsh area, often some near the junction north of Lagras if you follow the road past Harriet."},
    {"name": "Types of fish caught", "key": "mpgc_fish_caught_variety", "category": ["shops", "tackle"]},
    {"name": "Used an emote on a local", "key": "mpgc_emote_npc"},
    {"name": "Used an emote on a player in Free Roam", "key": "mpgc_emote_player"},
    {"name": "Vanilla Flowers picked", "key": "mpgc_vanilla_flower_picked", "category": ["plants", "vanilla_flower"]},
    {"name": "Vaults on horseback", "key": "mpgc_horse_vaults",
             "description": "Head to Tumbleweed, there's a nice low wall right by the fast travel post that you can use to vault over."},
    {"name": "Violet Snowdrop picked", "key": "mpgc_violet_snowdrop_picked", "category": ["plants", "violet_snowdrop"],
             "description": "On the clifftop above Valentine, there's a few patches up there."},
    {"name": "Virginia Opossums skinned", "key": "mpgc_opossums_skinned", "category": ["animal", "possum"],
             "description": "Hunt these at night only. Best spot is the trees just in front of Riggs Station.\nYou can also head to Rhodes and try in the woods just east of Mattock Pond.\nFinally, south of the abandoned village of Pleasance is another place to try."},
    {"name": "Visited a shop in Blackwater", "key": "mpgc_shop_visit_blackwater", "category": ["shops", "general_store"]},
    {"name": "Visited a shop in Rhodes", "key": "mpgc_shop_visit_rhodes", "category": ["shops", "general_store"]},
    {"name": "Visited a shop in Saint Denis", "key": "mpgc_shop_visit_saint_denis", "category": ["shops", "general_store"]},
    {"name": "Visited a shop in Strawberry", "key": "mpgc_shop_visit_strawberry", "category": ["shops", "general_store"]},
    {"name": "Visited a shop in Tumbleweed", "key": "mpgc_shop_visit_tumbleweed", "category": ["shops", "general_store"]},
    {"name": "Visited a shop in Valentine", "key": "mpgc_shop_visit_valentine", "category": ["shops", "general_store"]},
    {"name": "Visited Annesburg and Armadillo in an hour", "key": "mpgc_travel_timed_annesburg_armadillo"},
    {"name": "Visited Bolger Glade", "key": "mpgc_travel_visit_bolger_glade", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Brandywine Drop", "key": "mpgc_travel_visit_brandywine_drop", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Colter and Saint Denis in an hour", "key": "mpgc_travel_timed_colter_saint_denis"},
    {"name": "Visited Colter", "key": "mpgc_travel_visit_colter", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Cotorra springs", "key": "mpgc_travel_visit_cotorra_springs", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Fort Mercer", "key": "mpgc_travel_visit_fort_mercer", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Fort Wallace", "key": "mpgc_travel_visit_fort_wallace", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Lagras", "key": "mpgc_travel_visit_lagras", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited MacFarlane's Ranch", "key": "mpgc_travel_visit_macfarlane_ranch", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Owanjila Dam", "key": "mpgc_travel_visit_owanjila_dam", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited the peak of Mount Hagen", "key": "mpgc_travel_visit_mount_hagen", "category": ["daily_location", "daily_locations"]},
    {"name": "Visited Valentine and Van Horn in 30 mins", "key": "mpgc_travel_timed_valentine_van_horn"},
    {"name": "Visited Van Horn", "key": "mpgc_travel_visit_van_horn", "category": ["daily_location", "daily_locations"]},
    {"name": "Vultures plucked", "key": "mpgc_vultures_skinned", "category": ["animal", "vulture_western"],
             "description": "Head to Armadillo and then go north along the railway line road, you often see one perched on top of the telegraph poles there.\nSwap lobbies to get more spawns."},
    {"name": "Waves completed in Call to Arms", "key": "mpgc_protect_waves_completed", "showgoal": "yes"},
    {"name": "Weapons cleaned with Gun Oil", "key": "mpgc_customization_weapon_cleaning", "category": ["shops", "gunsmith"]},
    {"name": "Weapons customized", "key": "mpgc_customization_weapon_customization", "category": ["shops", "gunsmith"], "showgoal": "yes"},
    {"name": "Western Chipmunks collected", "key": "mpgc_chipmunk_skinned", "category": ["animal", "chipmunk"],
             "description": "Fast travel to Manzanita Post, then head north till you get to the little triangle junction. There's usually a couple of chipmunks in the grass at the centre."},
    {"name": "Western Ravens plucked", "key": "mpgc_ravens_skinned", "category": ["animal", "raven"],
             "description": "Ravens can be found all over the map. Try killing an animal and leaving the carcass,\nmaybe use some predator bait nearby. That will often draw them in to your location."},
    {"name": "Western Toads collected", "key": "mpgc_toads_skinned", "category": ["animal", "toad"],
             "description": "Follow the railway tracks north out of the city and into Bluewater Marsh.\nThe mud flats near where the railway line forks over the water is a good place to hunt for toads.\nSo is the area near the burnt out fishing shack at Copperhead Landing, just NE of that."},
    {"name": "Whole animal carcasses sold", "key": "mpgc_shop_animal_whole_sell", "category": ["shops", "butcher"],
             "description": "Sell at any butchers, ones at Blackwater and Rhodes are very close to the fast travel posts."},
    {"name": "Whooping Cranes plucked", "key": "mpgc_cranewhooping_skinned", "category": ["animal", "cranewhooping_whooping"],
             "description": "From Blackwater, go south to Quaker's Cove, and as you come down the approach road, to the left\nis a small beach, often with Whooping Cranes at the waters edge. Change lobbies to get respawns.\nAlso Copperhead Landing at the east edge of Bluewater Marsh is a good area."},
    {"name": "Wild Carrots picked", "key": "mpgc_wild_carrots_picked", "category": ["plants", "wild_carrots"],
             "description": "Fast travel to Armadillo, head south-west, beside the two cactii at the railroad crossing is a patch.\nContinue south west and just across the next path is some more, there's plenty around."},
    {"name": "Wild Feverfew picked", "key": "mpgc_wild_feverfew_picked", "category": ["plants", "wild_feverfew"],
             "description": "Fast travel to Armadillo, walk a few metres to the first telegraph pole south of the station, and cross\nthe tracks to your right. There's a patch here, then head directly west for two more patches nearby."},
    {"name": "Wild Mint picked", "key": "mpgc_wild_mint_picked", "category": ["plants", "wild_mint"],
             "description": "Just to the east of the southern road out of Blackwater, there's a number of plants around the boundary line."},
    {"name": "Wintergreen Berries picked", "key": "mpgc_wintergreen_berry_picked", "category": ["plants", "wintergreen_berry"],
             "description": "Cumberland Forest, north east of Valentine, is the best place to find them.\nThere's a good patch around the road the runs through 'FOREST' on the map"},
    {"name": "Wolves killed", "key": "mpgc_wolves_killed", "category": ["animal", "wolf_gray"],
             "description": "Wolves often attack between Fort Riggs and Riggs Station. Try Tall Trees, east of Aurora Basin.\nAbove MacFarlane's Ranch on the road to Harriet's, or by the railway south-east of the ranch.\nCumberland Forest can be a good location. Generally wolves tend to be out at night."},
    {"name": "Yarrow picked", "key": "mpgc_yarrow_picked", "category": ["plants", "yarrow"],
             "description": "Fast travel to Rhodes station, and on the grass area to the west, there are two patches of yarrow.\nOne is opposite the platform beside the southern path, and the next is further south-east opposite the funeral parlour."}
]
 
trader = [
    {"name": "Camp Stews eaten", "key": "mprc_trader_stew_eaten"},
    {"name": "Carcasses donated within 10 minutes", "key": "mprc_trader_sold_carcass_timed"},
    {"name": "Cripps Special Camp Stew recipes completed", "key": "mprc_trader_stew_recipe_completed_cripps", "showgoal": "yes"},
    {"name": "Distance Delivery Wagon traveled on mission", "key": "mprc_trader_travel_wagon",
             "description": "Use a Change Appearance solo lobby so it registers"},
    {"name": "Donated deadly predator carcass or skin", "key": "mprc_trader_supplies_donated_predator"},
    {"name": "Donations to Cripps", "key": "mprc_trader_supplies_donated"},
    {"name": "Goods sold to distant buyer", "key": "mprc_trader_goods_sold_far_away"},
    {"name": "Goods sold to local buyer", "key": "mprc_trader_goods_sold_local", "showgoal": "yes"},
    {"name": "High Quality Camp Stew recipes completed", "key": "mprc_trader_stew_recipe_completed_high"},
    {"name": "Large animal carcasses donated to Cripps", "key": "mprc_trader_supplies_donated_animal_large",
             "description": "Deer, Pronghorn, Bighorn Ram, Panther, Cougar, Wolf"},
    {"name": "Medium animal carcasses donated to Cripps", "key": "mprc_trader_supplies_donated_animal_medium",
             "description": "Emerald Ranch, for sheep, turkeys, & foxes.\nRacoons, Geese, Cranes, Herons, & Pelicans"},
    {"name": "Money made from trading", "key": "mprc_trader_money_made", "showgoal": "yes"},
    {"name": "Perfect carcasses donated to Cripps", "key": "mprc_trader_supplies_donated_carcass_perfect",
             "description": "Perfect pelts don't count. Try Emerald Ranch sheep."},
    {"name": "Resupply completed with 3 mins left", "key": "mprc_trader_resupply_completed_timed_easy", "showgoal": "yes"},
    {"name": "Resupply completed with 4 mins left", "key": "mprc_trader_resupply_completed_timed_med", "showgoal": "yes"},
    {"name": "Resupply completed with 5 mins left", "key": "mprc_trader_resupply_completed_timed_hard", "showgoal": "yes"},
    {"name": "Resupply missions completed", "key": "mprc_trader_resupply_completed", "showgoal": "yes",
             "description": "Buggy, often won't register"},
    {"name": "Small animal carcasses donated to Cripps", "key": "mprc_trader_supplies_donated_animal_small", "showgoal": "yes"},
    {"name": "Superior Quality Camp Stew recipes completed", "key": "mprc_trader_stew_recipe_completed_superior", "showgoal": "yes"}
  ]
 
collector = [
    {"name": "American Wild Flowers found", "key": "mprc_collector_wild_flowers_found", "showgoal": "yes"},
    {"name": "Antique Alcohol Bottles found", "key": "mprc_collector_antique_bottles_found", "category": ["menu", "moonshiner_roadblock"], "showgoal": "yes"},
    {"name": "Antique Alcohol drunk", "key": "mprc_collector_antique_alcohol_drunk", "category": ["menu", "moonshiner_roadblock"], "showgoal": "yes"},
    {"name": "Arrowheads found", "key": "mprc_collector_arrowheads_found", "showgoal": "yes"},
    {"name": "Bird Eggs found", "key": "mprc_collector_bird_eggs_found", "showgoal": "yes",
             "description": "Keep less than 5 duck eggs in your satchel, and you can then pick 5 of them at once"},
    {"name": "Coins found", "key": "mprc_collector_coins_found", "showgoal": "yes"},
    {"name": "Collectibles collected", "key": "mprc_collector_items_collected", "showgoal": "yes"},
    {"name": "Collectibles found with a Metal Detector", "key": "mprc_collector_used_metal_dectector", "showgoal": "yes"},
    {"name": "Collectibles found with a Shovel", "key": "mprc_collector_used_shovel", "showgoal": "yes"},
    {"name": "Collectibles looted from non-player enemies", "key": "mprc_collector_items_looted_enemy", "showgoal": "yes"},
    {"name": "Collectibles sold to Madam Nazar", "key": "mprc_collector_items_sold", "category": ["nazar", "madam_nazar"], "showgoal": "yes"},
    {"name": "Collector Maps used", "key": "mprc_collector_used_map", "category": ["nazar", "madam_nazar"], "showgoal": "yes"},
    {"name": "Family Heirlooms found", "key": "mprc_collector_family_heirlooms_found", "showgoal": "yes"},
    {"name": "Fossils found", "key": "mprc_collector_fossils_found", "showgoal": "yes"},
    {"name": "Lost Jewelry found", "key": "mprc_collector_lost_jewelry_found", "showgoal": "yes"},
    {"name": "Tarot Cards found", "key": "mprc_collector_tarot_cards_found", "showgoal": "yes"}
  ]
 
bounty_hunter = [
    {"name": "Bounties brought in from Lemoyne posters", "key": "mprc_bounty_location_lemoyne", "showgoal": "yes",
             "description": "Rhodes and Saint Denis"},
    {"name": "Bounties brought in from New Austin posters", "key": "mprc_bounty_location_new_austin", "showgoal": "yes",
             "description": "Armadillo, Tumbleweed and Benedict Point"},
    {"name": "Bounties brought in from New Hanover posters", "key": "mprc_bounty_location_new_hanover", "showgoal": "yes",
             "description": "Valentine, Emerald Station, Van Horn and Annesburg"},
    {"name": "Bounties brought in from West Elizabeth posters", "key": "mprc_bounty_location_west_elizabeth", "showgoal": "yes",
             "description": "Strawberry, Blackwater, Wallace Station, and Riggs Station"},
    {"name": "Bounties completed within one real-world hour", "key": "mprc_bounty_completed_timed", "showgoal": "yes"},
    {"name": "Bounty completed with at least one other Posse Member", "key": "mprc_bounty_completed_posse_member", "showgoal": "yes"},
    {"name": "Bounty completed without killing an enemy or bounty target", "key": "mprc_bounty_completed_no_kills",
             "description": "Risky, usually bugged and won't register"},
    {"name": "Bounty hunt completed with 3 min or more left", "key": "mprc_bounty_general_delivered_timed_easy"},
    {"name": "Bounty hunt completed with 4 min or more left", "key": "mprc_bounty_general_delivered_timed_med"},
    {"name": "Bounty hunt completed with 5 min or more left", "key": "mprc_bounty_general_delivered_timed_hard"},
    {"name": "Bounty targets brought in", "key": "mprc_bounty_general_delivered", "showgoal": "yes"},
    {"name": "Bounty targets hogtied with a Reinforced Lasso", "key": "mprc_bounty_used_reinforced_lasso", "showgoal": "yes"},
    {"name": "Bounty targets lassoed from horseback", "key": "mprc_bounty_used_lasso_horseback", "showgoal": "yes",
             "description": "Lasso the same target three times."},
    {"name": "Bounty targets looted", "key": "mprc_bounty_targets_looted", "showgoal": "yes"},
    {"name": "Bounty targets tagged with Tracking Arrow", "key": "mprc_bounty_used_track_arrow", "showgoal": "yes"},
    {"name": "Bounty targets taken down with Bolas", "key": "mprc_bounty_used_bolas", "showgoal": "yes"},
    {"name": "Eagle Eye used to track a bounty target", "key": "mprc_bounty_used_eagle_eye", "showgoal": "yes",
             "description": "Can shoot with tracking arrow and then track them"},
    {"name": "Easy ($) bounty mission completed", "key": "mprc_bounty_mission_completed_easy"},
    {"name": "Hard ($$$) or Legendary Bounty mission completed", "key": "mprc_bounty_mission_completed_hard", "showgoal": "yes"},
    {"name": "Living bounty targets in a photograph", "key": "mprc_bounty_target_photographed_alive", "showgoal": "yes"},
    {"name": "Medium ($$) bounty mission completed", "key": "mprc_bounty_mission_completed_medium"},
    {"name": "More than one bounty target brought in at once", "key": "mprc_bounty_general_delivered_multi_target", "showgoal": "yes"},
    {"name": "Player bounties collected", "key": "mprc_bounty_player_completed", "showgoal": "yes"}
  ]
 
moonshiner = [
    {"name": "Completed improved or better moonshine recipe", "key": "mprc_moonshiner_recipe_completed_med"},
    {"name": "Completed regular or better moonshine recipe", "key": "mprc_moonshiner_recipe_completed_easy"},
    {"name": "Completed special moonshine recipe", "key": "mprc_moonshiner_recipe_completed_hard"},
    {"name": "Crafted Toxic Moonshine", "key": "mprc_moonshiner_craft_poison_bottle"},
    {"name": "Distance Moonshine Wagon traveled on mission", "key": "mprc_moonshiner_travel_wagon", "showgoal": "yes"},
    {"name": "Drank own average or higher strength moonshine", "key": "mprc_moonshiner_moonshine_drank_med"},
    {"name": "Drank own strong moonshine", "key": "mprc_moonshiner_moonshine_drank_hard"},
    {"name": "Drank own weak or higher strength moonshine", "key": "mprc_moonshiner_moonshine_drank_easy"},
    {"name": "Money made from moonshine sold", "key": "mprc_moonshiner_money_made", "showgoal": "yes"},
    {"name": "Moonshine Bar - Changed décor", "key": "mprc_moonshiner_bar_changed_decor"},
    {"name": "Moonshine Bar - Danced for 1 min", "key": "mprc_moonshiner_danced_bar_med"},
    {"name": "Moonshine Bar - Danced for 2 mins", "key": "mprc_moonshiner_danced_bar_hard"},
    {"name": "Moonshine Bar - Drunken player interaction", "key": "mprc_moonshiner_drunk_interaction_bar",
             "description": "If solo, use Y then B button combo as entering shack", "showgoal": "yes"},
    {"name": "Moonshine Bar - Stayed for the last round", "key": "mprc_moonshiner_last_round_bar"},
    {"name": "Moonshine Bootlegger Missions completed", "key": "mprc_moonshiner_marketing_mission_completed", "showgoal": "yes"},
    {"name": "Moonshine of any type sold to a buyer", "key": "mprc_moonshiner_moonshine_sold_buyer"},
    {"name": "Moonshine of preferred type sold to a buyer", "key": "mprc_moonshiner_moonshine_sold_buyer_hard", "showgoal": "yes"},
    {"name": "Moonshine served to other players at a bar", "key": "mprc_moonshiner_moonshine_served_bar", "showgoal": "yes"},
    {"name": "Moonshine sold with 3 mins left", "key": "mprc_moonshiner_moonshine_sold_buyer_timed_easy"},
    {"name": "Moonshine sold with 4 mins left", "key": "mprc_moonshiner_moonshine_sold_buyer_timed_med"},
    {"name": "Moonshine sold with 5 mins left", "key": "mprc_moonshiner_moonshine_sold_buyer_timed_hard"},
    {"name": "Moonshine sold with at least 10 bottles intact", "key": "mprc_moonshiner_moonshine_sold_buyer_condition_easy"},
    {"name": "Moonshine sold with at least 15 bottles intact", "key": "mprc_moonshiner_moonshine_sold_buyer_condition_med"},
    {"name": "Moonshine sold with at least 18 bottles intact", "key": "mprc_moonshiner_moonshine_sold_buyer_condition_hard"},
    {"name": "Moonshine Story Mission completed", "key": "mprc_moonshiner_story_mission_completed", "showgoal": "yes"},
    {"name": "Played with a band for 1 min", "key": "mprc_moonshiner_band_played_med"},
    {"name": "Played with a band for 2 mins", "key": "mprc_moonshiner_band_played_hard"}
  ]

naturalist = [
    {"name": "Animal samples sold to Harriet", "key": "mprc_naturalist_samples_sold", "showgoal": "yes"},
    {"name": "Animal samples taken within 10 mins", "key": "mprc_naturalist_samples_taken_timed", "showgoal": "yes"},
    {"name": "Blending Tonics crafted or used", "key": "mprc_naturalist_crafted_blending_tonic", "showgoal": "yes"},
    {"name": "Crafted or cooked at Wilderness Camp", "key": "mprc_naturalist_crafted_cooked_wilderness_camp", "showgoal": "yes"},
    {"name": "Desert animal samples taken", "key": "mprc_naturalist_sample_animal_desert", "showgoal": "yes"},
    {"name": "Don't kill an animal for 12 game hours", "key": "mprc_naturalist_dont_kill_animals_easy"},
    {"name": "Don't kill an animal for 18 game hours", "key": "mprc_naturalist_dont_kill_animals_med"},
    {"name": "Don't kill an animal for 24 game hours", "key": "mprc_naturalist_dont_kill_animals_hard"},
    {"name": "Farmland animal samples taken", "key": "mprc_naturalist_sample_animal_domesticated", "showgoal": "yes"},
    {"name": "Forest/River animal samples taken", "key": "mprc_naturalist_sample_animal_forest", "showgoal": "yes"},
    {"name": "Hardy Tonics used when too hot or cold", "key": "mprc_naturalist_used_hardy_tonic", "showgoal": "yes"},
    {"name": "Legendary Animal samples taken", "key": "mprc_naturalist_sample_animal_legendary", "showgoal": "yes"},
    {"name": "Legendary Animals found using pheromones", "key": "mprc_naturalist_used_legendary_bait", "showgoal": "yes"},
    {"name": "Legendary Animals photographed", "key": "mprc_naturalist_photo_animal_legendary", "showgoal": "yes"},
    {"name": "Mountain/Grassland animal samples taken", "key": "mprc_naturalist_sample_animal_grassland", "showgoal": "yes"},
    {"name": "Sedated animals revived", "key": "mprc_naturalist_tranq_animal_revived", "showgoal": "yes"},
    {"name": "Weight Change Tonics used", "key": "mprc_naturalist_used_weight_tonic", "showgoal": "yes"},
    {"name": "Wetland animal samples taken", "key": "mprc_naturalist_sample_animal_swamp", "showgoal": "yes"}
  ]

