name: RDO Dailies v2

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 07:00 UTC every day
  push:
    # optional: trigger manually or on other events

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    #- name: Install dependencies
    #  run: |
    #    pip install -r requirements.txt  # if you have dependencies

    - name: Run script to generate index.html
      run: |
        python RDO_dailies_v2.py

    - name: Commit and push generated file
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add index.html
        git commit -m "Update index.html" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}